keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(1.25, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(1.25, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("6", x, bpm)
rest(1.5, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(1.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(1.25, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(1.25, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(1.25, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("o", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("d", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.75, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.648, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.648, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.432, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("0", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("u", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.216, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.216, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("0", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("u", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.216, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.216, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("e", x, bpm)
rest(0.432, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("E", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("E", x, bpm)
rest(0.432, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
rest(0.216, bpm)
keypress("y", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("y", x, bpm)
rest(0.216, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("y", x, bpm)
rest(0.432, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("i", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.864, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.864, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(0.432, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.432, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("E", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("E", x, bpm)
rest(0.432, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
rest(0.216, bpm)
keypress("y", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("y", x, bpm)
rest(0.216, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("y", x, bpm)
rest(0.432, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("i", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.216, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("6", x, bpm)
rest(1.296, bpm)
keypress("1", x, bpm)
rest(0.216, bpm)
keypress("3", x, bpm)
rest(0.216, bpm)
keypress("6", x, bpm)
rest(0.648, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("1", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("0", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.432, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("1", x, bpm)
rest(0.216, bpm)
keypress("3", x, bpm)
rest(0.216, bpm)
keypress("6", x, bpm)
rest(1.296, bpm)
keypress("8", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("3", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
keypress("1", x, bpm)
rest(0.216, bpm)
keypress("0", x, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("2", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
keypress("4", x, bpm)
rest(0.216, bpm)
keypress("0", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.648, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.432, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("q", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("q", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.648, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("8", x, bpm)
rest(0.216, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("q", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("o", x, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("q", x, bpm)
rest(0.216, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("q", x, bpm)
rest(0.216, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("q", x, bpm)
rest(0.216, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("q", x, bpm)
rest(0.216, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("o", x, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("o", x, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("0", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("t", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("9", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("q", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("9", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("9", x, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.108, bpm)
keypress("w", x, bpm)
rest(0.108, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("0", x, bpm)
rest(0.216, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("0", x, bpm)
rest(0.216, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.432, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("q", x, bpm)
rest(0.216, bpm)
keypress("9", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(0.432, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("8", x, bpm)
rest(0.216, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("w", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("0", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("u", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.216, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.216, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("u", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.216, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.216, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("0", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("E", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("E", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("y", x, bpm)
rest(0.216, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("y", x, bpm)
rest(0.432, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("w", x, bpm)
rest(0.432, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("0", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("6", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("E", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("E", x, bpm)
rest(0.432, bpm)
keypress("^", x, bpm)
rest(0.432, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("y", x, bpm)
rest(0.216, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("y", x, bpm)
rest(0.432, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.432, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("w", x, bpm)
rest(0.432, bpm)
keypress("5", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.216, bpm)
keypress("5", x, bpm)
rest(0.216, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.216, bpm)
keypress("w", x, bpm)
rest(0.432, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)

finishedSong()