keypress("3", x, bpm)
rest(0.75, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(0.75, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
rest(0.75, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
rest(0.75, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
rest(0.75, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
rest(0.75, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.75, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
rest(0.75, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.75, bpm)
keypress("I", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.75, bpm)
keypress("T", x, bpm)
keypress("W", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
rest(0.75, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.75, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.75, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
rest(0.75, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.75, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.75, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(0.75, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)

finishedSong()