keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(1.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.167, bpm)
keypress("u", x, bpm)
rest(0.167, bpm)
keypress("y", x, bpm)
rest(0.167, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.167, bpm)
keypress("u", x, bpm)
rest(0.167, bpm)
keypress("y", x, bpm)
rest(0.167, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.75, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1.5, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.167, bpm)
keypress("p", x, bpm)
rest(0.167, bpm)
keypress("o", x, bpm)
rest(0.167, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(1.998, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(0.179, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.179, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.179, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.179, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.179, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.179, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.179, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.179, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.179, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.179, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.179, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.179, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(0.166, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.166, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.166, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.166, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.166, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.166, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.166, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.166, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.166, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.166, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.166, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.166, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
rest(0.154, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.154, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.154, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.154, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.154, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.154, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.154, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.154, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.154, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.154, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.154, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.154, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("I", x, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
rest(0.289, bpm)
keypress("y", x, bpm)
rest(0.001, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("6", x, bpm)
rest(0.29, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.29, bpm)
keypress("1", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.29, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.193, bpm)
keypress("1", x, bpm)
rest(0.29, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.193, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.29, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.193, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("1", x, bpm)
rest(0.29, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.29, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.193, bpm)
keypress("1", x, bpm)
rest(0.29, bpm)
keypress("u", x, bpm)
keypress("1", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.29, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.193, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("@", x, bpm)
rest(0.29, bpm)
keypress("@", x, bpm)
rest(0.193, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.29, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("@", x, bpm)
rest(0.29, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(0.193, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.29, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.29, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("3", x, bpm)
rest(0.29, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("4", x, bpm)
rest(0.29, bpm)
keypress("Y", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("$", x, bpm)
rest(0.29, bpm)
keypress("Y", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
rest(0.289, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.001, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("6", x, bpm)
rest(0.29, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("^", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.29, bpm)
keypress("1", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.29, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.193, bpm)
keypress("1", x, bpm)
rest(0.29, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.193, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.29, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.193, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("1", x, bpm)
rest(0.29, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.29, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.193, bpm)
keypress("1", x, bpm)
rest(0.29, bpm)
keypress("u", x, bpm)
keypress("1", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.29, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.193, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("@", x, bpm)
rest(0.29, bpm)
keypress("@", x, bpm)
rest(0.193, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.29, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("@", x, bpm)
rest(0.29, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(0.193, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.29, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.29, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("3", x, bpm)
rest(0.29, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("4", x, bpm)
rest(0.29, bpm)
keypress("Y", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("$", x, bpm)
rest(0.29, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("6", x, bpm)
rest(0.289, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("D", x, bpm)
rest(0.001, bpm)
keypress("7", x, bpm)
rest(0.483, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.193, bpm)
keypress("p", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.29, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.193, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
rest(0.29, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.193, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.29, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.193, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
rest(0.29, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.193, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
rest(0.29, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.193, bpm)
keypress("3", x, bpm)
rest(0.29, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.193, bpm)
keypress("3", x, bpm)
rest(0.289, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
rest(0.001, bpm)
keypress("@", x, bpm)
rest(0.483, bpm)
keypress("6", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
rest(0.29, bpm)
keypress("6", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.29, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.193, bpm)
keypress("2", x, bpm)
rest(0.483, bpm)
keypress("2", x, bpm)
rest(0.29, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
rest(0.193, bpm)
keypress("2", x, bpm)
rest(0.29, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("3", x, bpm)
rest(0.193, bpm)
keypress("3", x, bpm)
rest(0.483, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.161, bpm)
keypress("O", x, bpm)
rest(0.161, bpm)
keypress("s", x, bpm)
rest(0.161, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.161, bpm)
keypress("s", x, bpm)
rest(0.161, bpm)
keypress("f", x, bpm)
rest(0.161, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.161, bpm)
keypress("f", x, bpm)
rest(0.161, bpm)
keypress("H", x, bpm)
rest(0.161, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.29, bpm)
keypress("6", x, bpm)
rest(0.193, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.29, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.193, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("6", x, bpm)
rest(0.29, bpm)
keypress("6", x, bpm)
rest(0.193, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.29, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.193, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("2", x, bpm)
rest(0.29, bpm)
keypress("2", x, bpm)
rest(0.193, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.29, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.193, bpm)
keypress("2", x, bpm)
rest(0.29, bpm)
keypress("2", x, bpm)
rest(0.193, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.29, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.193, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.129, bpm)
keypress("5", x, bpm)
rest(0.032, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.129, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.032, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.129, bpm)
keypress("5", x, bpm)
rest(0.032, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.129, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.032, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.129, bpm)
keypress("3", x, bpm)
rest(0.032, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.129, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.032, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.129, bpm)
keypress("3", x, bpm)
rest(0.032, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.129, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.032, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.161, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.483, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.483, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.483, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
rest(0.483, bpm)
keypress("9", x, bpm)
rest(0.322, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.161, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.322, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.161, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.322, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.161, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.322, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.161, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("I", x, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
rest(0.289, bpm)
keypress("y", x, bpm)
rest(0.001, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("6", x, bpm)
rest(0.29, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.29, bpm)
keypress("1", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.29, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.193, bpm)
keypress("1", x, bpm)
rest(0.29, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.193, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.29, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.193, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("1", x, bpm)
rest(0.29, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.29, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.193, bpm)
keypress("1", x, bpm)
rest(0.29, bpm)
keypress("u", x, bpm)
keypress("1", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.29, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.193, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("@", x, bpm)
rest(0.29, bpm)
keypress("@", x, bpm)
rest(0.193, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.29, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("@", x, bpm)
rest(0.29, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(0.193, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.29, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.29, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("3", x, bpm)
rest(0.29, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("4", x, bpm)
rest(0.29, bpm)
keypress("Y", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("$", x, bpm)
rest(0.29, bpm)
keypress("Y", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
rest(0.289, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.001, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("6", x, bpm)
rest(0.29, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("^", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.29, bpm)
keypress("1", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.29, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.193, bpm)
keypress("1", x, bpm)
rest(0.29, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.193, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.29, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.193, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("1", x, bpm)
rest(0.29, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.29, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.193, bpm)
keypress("1", x, bpm)
rest(0.29, bpm)
keypress("u", x, bpm)
keypress("1", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.29, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.193, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("@", x, bpm)
rest(0.29, bpm)
keypress("@", x, bpm)
rest(0.193, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.29, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("@", x, bpm)
rest(0.29, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(0.193, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.29, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.29, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("3", x, bpm)
rest(0.29, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("4", x, bpm)
rest(0.29, bpm)
keypress("Y", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("$", x, bpm)
rest(0.29, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("6", x, bpm)
rest(0.289, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("D", x, bpm)
rest(0.001, bpm)
keypress("7", x, bpm)
rest(0.483, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.193, bpm)
keypress("p", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.29, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.193, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
rest(0.29, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.193, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.29, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.193, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
rest(0.29, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.193, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
rest(0.29, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.193, bpm)
keypress("3", x, bpm)
rest(0.29, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.193, bpm)
keypress("3", x, bpm)
rest(0.289, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
rest(0.001, bpm)
keypress("@", x, bpm)
rest(0.483, bpm)
keypress("6", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
rest(0.29, bpm)
keypress("6", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.29, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.193, bpm)
keypress("2", x, bpm)
rest(0.483, bpm)
keypress("2", x, bpm)
rest(0.29, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
rest(0.193, bpm)
keypress("2", x, bpm)
rest(0.29, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("3", x, bpm)
rest(0.193, bpm)
keypress("3", x, bpm)
rest(0.483, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.161, bpm)
keypress("O", x, bpm)
rest(0.161, bpm)
keypress("s", x, bpm)
rest(0.161, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.161, bpm)
keypress("s", x, bpm)
rest(0.161, bpm)
keypress("f", x, bpm)
rest(0.161, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.161, bpm)
keypress("f", x, bpm)
rest(0.161, bpm)
keypress("H", x, bpm)
rest(0.161, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.29, bpm)
keypress("6", x, bpm)
rest(0.193, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.29, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.193, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("6", x, bpm)
rest(0.29, bpm)
keypress("6", x, bpm)
rest(0.193, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.29, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.193, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("2", x, bpm)
rest(0.29, bpm)
keypress("2", x, bpm)
rest(0.193, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.29, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.193, bpm)
keypress("2", x, bpm)
rest(0.29, bpm)
keypress("2", x, bpm)
rest(0.193, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.29, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.193, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.129, bpm)
keypress("5", x, bpm)
rest(0.032, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.129, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.032, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.129, bpm)
keypress("5", x, bpm)
rest(0.032, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.129, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.032, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.129, bpm)
keypress("3", x, bpm)
rest(0.032, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.129, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.032, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.129, bpm)
keypress("3", x, bpm)
rest(0.032, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.129, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.032, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.161, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.483, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.483, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.483, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
rest(0.483, bpm)
keypress("9", x, bpm)
rest(0.322, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.161, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.322, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.161, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.322, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.161, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.322, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.161, bpm)
keypress("u", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("I", x, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
rest(0.289, bpm)
keypress("y", x, bpm)
rest(0.001, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("6", x, bpm)
rest(0.29, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.29, bpm)
keypress("1", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.29, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.193, bpm)
keypress("1", x, bpm)
rest(0.29, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.193, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.29, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.193, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("1", x, bpm)
rest(0.29, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.29, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.193, bpm)
keypress("1", x, bpm)
rest(0.29, bpm)
keypress("u", x, bpm)
keypress("1", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.29, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.193, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("@", x, bpm)
rest(0.29, bpm)
keypress("@", x, bpm)
rest(0.193, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.29, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("@", x, bpm)
rest(0.29, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(0.193, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.29, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.29, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("3", x, bpm)
rest(0.29, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("4", x, bpm)
rest(0.29, bpm)
keypress("Y", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("$", x, bpm)
rest(0.29, bpm)
keypress("Y", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
rest(0.289, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.001, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("6", x, bpm)
rest(0.289, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.001, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("^", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.29, bpm)
keypress("1", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.29, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.193, bpm)
keypress("1", x, bpm)
rest(0.29, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
rest(0.193, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.29, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.193, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("1", x, bpm)
rest(0.29, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.29, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.193, bpm)
keypress("1", x, bpm)
rest(0.29, bpm)
keypress("u", x, bpm)
keypress("1", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.29, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.193, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("@", x, bpm)
rest(0.29, bpm)
keypress("@", x, bpm)
rest(0.193, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.29, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("@", x, bpm)
rest(0.29, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(0.193, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.29, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.29, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("3", x, bpm)
rest(0.29, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("4", x, bpm)
rest(0.29, bpm)
keypress("Y", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("$", x, bpm)
rest(0.29, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("6", x, bpm)
rest(0.289, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("D", x, bpm)
rest(0.001, bpm)
keypress("7", x, bpm)
rest(0.483, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.193, bpm)
keypress("p", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.29, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.193, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
rest(0.29, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.193, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.29, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.193, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
rest(0.29, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.193, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
rest(0.29, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.193, bpm)
keypress("3", x, bpm)
rest(0.29, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.193, bpm)
keypress("3", x, bpm)
rest(0.289, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
rest(0.001, bpm)
keypress("@", x, bpm)
rest(0.483, bpm)
keypress("6", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
rest(0.29, bpm)
keypress("6", x, bpm)
keypress("(", x, bpm)
rest(0.193, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.29, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.193, bpm)
keypress("2", x, bpm)
rest(0.483, bpm)
keypress("2", x, bpm)
rest(0.29, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
rest(0.193, bpm)
keypress("2", x, bpm)
rest(0.29, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("3", x, bpm)
rest(0.193, bpm)
keypress("3", x, bpm)
rest(0.483, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.161, bpm)
keypress("O", x, bpm)
rest(0.161, bpm)
keypress("s", x, bpm)
rest(0.161, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.161, bpm)
keypress("s", x, bpm)
rest(0.161, bpm)
keypress("f", x, bpm)
rest(0.161, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.161, bpm)
keypress("f", x, bpm)
rest(0.161, bpm)
keypress("H", x, bpm)
rest(0.161, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.29, bpm)
keypress("6", x, bpm)
rest(0.193, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.29, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.193, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("6", x, bpm)
rest(0.29, bpm)
keypress("6", x, bpm)
rest(0.193, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.29, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.193, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.483, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("j", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.966, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.966, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.966, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.483, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("3", x, bpm)
rest(0.29, bpm)
keypress("3", x, bpm)
rest(0.193, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.29, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.193, bpm)
keypress("3", x, bpm)
rest(0.29, bpm)
keypress("3", x, bpm)
rest(0.193, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.29, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.193, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.29, bpm)
keypress("6", x, bpm)
rest(0.193, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.29, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.193, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.29, bpm)
keypress("6", x, bpm)
rest(0.193, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.29, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.193, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("2", x, bpm)
rest(0.29, bpm)
keypress("2", x, bpm)
rest(0.193, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.29, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.193, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.29, bpm)
keypress("2", x, bpm)
rest(0.193, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.29, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("3", x, bpm)
rest(0.29, bpm)
keypress("3", x, bpm)
rest(0.193, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.29, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.193, bpm)
keypress("3", x, bpm)
rest(0.29, bpm)
keypress("3", x, bpm)
rest(0.193, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.29, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.193, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.29, bpm)
keypress("6", x, bpm)
rest(0.193, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.29, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.193, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.29, bpm)
keypress("6", x, bpm)
rest(0.193, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.29, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.193, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("2", x, bpm)
rest(0.29, bpm)
keypress("2", x, bpm)
rest(0.193, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.29, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.193, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.29, bpm)
keypress("2", x, bpm)
rest(0.193, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.29, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.193, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.193, bpm)
keypress("5", x, bpm)
rest(0.29, bpm)
keypress("5", x, bpm)
rest(0.193, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.29, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.515, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.161, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.322, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.161, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.322, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.161, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.322, bpm)
keypress("2", x, bpm)
rest(0.161, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)

finishedSong()