keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.75, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.857, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("(", x, bpm)
rest(0.643, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("(", x, bpm)
rest(0.857, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("7", x, bpm)
rest(0.643, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("*", x, bpm)
rest(0.857, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.643, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.857, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
rest(0.214, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
rest(0.429, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("(", x, bpm)
rest(0.643, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("(", x, bpm)
rest(0.857, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.857, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.214, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
rest(0.214, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
rest(0.214, bpm)
keypress("Y", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("S", x, bpm)
rest(0.214, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("S", x, bpm)
rest(0.214, bpm)
keypress("S", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.214, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
rest(0.214, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
rest(0.214, bpm)
keypress("Y", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.214, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.857, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
rest(0.214, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.643, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.857, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
rest(0.429, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.643, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.857, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
rest(0.214, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.643, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.857, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.643, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.857, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("k", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("L", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("!", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("k", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("L", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("B", x, bpm)
rest(0.025, bpm)
keypress("b", x, bpm)
rest(0.027, bpm)
keypress("V", x, bpm)
rest(0.029, bpm)
keypress("v", x, bpm)
rest(0.025, bpm)
keypress("C", x, bpm)
rest(0.027, bpm)
keypress("c", x, bpm)
rest(0.029, bpm)
keypress("x", x, bpm)
rest(0.025, bpm)
keypress("Z", x, bpm)
rest(0.027, bpm)
keypress("z", x, bpm)
rest(0.029, bpm)
keypress("L", x, bpm)
rest(0.025, bpm)
keypress("l", x, bpm)
rest(0.027, bpm)
keypress("k", x, bpm)
rest(0.029, bpm)
keypress("J", x, bpm)
rest(0.025, bpm)
keypress("j", x, bpm)
rest(0.027, bpm)
keypress("H", x, bpm)
rest(0.029, bpm)
keypress("h", x, bpm)
rest(0.025, bpm)
keypress("G", x, bpm)
rest(0.027, bpm)
keypress("g", x, bpm)
rest(0.029, bpm)
keypress("f", x, bpm)
rest(0.025, bpm)
keypress("D", x, bpm)
rest(0.027, bpm)
keypress("d", x, bpm)
rest(0.029, bpm)
keypress("S", x, bpm)
rest(0.025, bpm)
keypress("s", x, bpm)
rest(0.027, bpm)
keypress("a", x, bpm)
rest(0.029, bpm)
keypress("P", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.857, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.857, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.857, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(1.286, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.214, bpm)
keypress("*", x, bpm)
rest(0.214, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.214, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
rest(0.214, bpm)
keypress("*", x, bpm)
rest(0.214, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.214, bpm)
keypress("*", x, bpm)
rest(0.214, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.214, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
rest(0.214, bpm)
keypress("*", x, bpm)
rest(0.214, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
rest(0.429, bpm)
keypress("0", x, bpm)
rest(0.429, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
rest(0.429, bpm)
keypress("0", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.857, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("k", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("L", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("!", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("k", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("L", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("B", x, bpm)
rest(0.025, bpm)
keypress("b", x, bpm)
rest(0.027, bpm)
keypress("V", x, bpm)
rest(0.029, bpm)
keypress("v", x, bpm)
rest(0.025, bpm)
keypress("C", x, bpm)
rest(0.027, bpm)
keypress("c", x, bpm)
rest(0.029, bpm)
keypress("x", x, bpm)
rest(0.025, bpm)
keypress("Z", x, bpm)
rest(0.027, bpm)
keypress("z", x, bpm)
rest(0.029, bpm)
keypress("L", x, bpm)
rest(0.025, bpm)
keypress("l", x, bpm)
rest(0.027, bpm)
keypress("k", x, bpm)
rest(0.029, bpm)
keypress("J", x, bpm)
rest(0.025, bpm)
keypress("j", x, bpm)
rest(0.027, bpm)
keypress("H", x, bpm)
rest(0.029, bpm)
keypress("h", x, bpm)
rest(0.025, bpm)
keypress("G", x, bpm)
rest(0.027, bpm)
keypress("g", x, bpm)
rest(0.029, bpm)
keypress("f", x, bpm)
rest(0.025, bpm)
keypress("D", x, bpm)
rest(0.027, bpm)
keypress("d", x, bpm)
rest(0.029, bpm)
keypress("S", x, bpm)
rest(0.025, bpm)
keypress("s", x, bpm)
rest(0.027, bpm)
keypress("a", x, bpm)
rest(0.029, bpm)
keypress("P", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.857, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.857, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.857, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.857, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.857, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.857, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.857, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.034, bpm)
keypress("i", x, bpm)
rest(0.036, bpm)
keypress("u", x, bpm)
rest(0.037, bpm)
keypress("Y", x, bpm)
rest(0.034, bpm)
keypress("y", x, bpm)
rest(0.036, bpm)
keypress("T", x, bpm)
rest(0.037, bpm)
keypress("t", x, bpm)
rest(0.034, bpm)
keypress("r", x, bpm)
rest(0.036, bpm)
keypress("E", x, bpm)
rest(0.037, bpm)
keypress("e", x, bpm)
rest(0.034, bpm)
keypress("W", x, bpm)
rest(0.036, bpm)
keypress("w", x, bpm)
rest(0.037, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.643, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("C", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.857, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.643, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("x", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.429, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.429, bpm)
keypress("x", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.857, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.643, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("C", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.857, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.643, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("C", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("C", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.857, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("C", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("x", x, bpm)
keypress("3", x, bpm)
rest(0.429, bpm)
keypress("0", x, bpm)
rest(0.429, bpm)
keypress("x", x, bpm)
keypress("3", x, bpm)
rest(0.429, bpm)
keypress("0", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("C", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("C", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("C", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.214, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.643, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.857, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.643, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.857, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.214, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.643, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.857, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.057, bpm)
keypress("y", x, bpm)
rest(0.059, bpm)
keypress("Y", x, bpm)
rest(0.059, bpm)
keypress("u", x, bpm)
rest(0.059, bpm)
keypress("i", x, bpm)
rest(0.059, bpm)
keypress("I", x, bpm)
rest(0.059, bpm)
keypress("o", x, bpm)
rest(0.059, bpm)
keypress("O", x, bpm)
rest(0.018, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.043, bpm)
keypress("p", x, bpm)
rest(0.057, bpm)
keypress("P", x, bpm)
rest(0.059, bpm)
keypress("a", x, bpm)
rest(0.059, bpm)
keypress("s", x, bpm)
rest(0.059, bpm)
keypress("S", x, bpm)
rest(0.059, bpm)
keypress("d", x, bpm)
rest(0.059, bpm)
keypress("D", x, bpm)
rest(0.034, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.025, bpm)
keypress("f", x, bpm)
rest(0.061, bpm)
keypress("g", x, bpm)
rest(0.057, bpm)
keypress("G", x, bpm)
rest(0.059, bpm)
keypress("h", x, bpm)
rest(0.059, bpm)
keypress("H", x, bpm)
rest(0.059, bpm)
keypress("j", x, bpm)
rest(0.059, bpm)
keypress("J", x, bpm)
rest(0.059, bpm)
keypress("k", x, bpm)
rest(0.059, bpm)
keypress("l", x, bpm)
rest(0.061, bpm)
keypress("L", x, bpm)
rest(0.057, bpm)
keypress("z", x, bpm)
rest(0.029, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.03, bpm)
keypress("Z", x, bpm)
rest(0.059, bpm)
keypress("x", x, bpm)
rest(0.059, bpm)
keypress("c", x, bpm)
rest(0.066, bpm)
keypress("C", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.016, bpm)
keypress("c", x, bpm)
rest(0.018, bpm)
keypress("x", x, bpm)
rest(0.02, bpm)
keypress("Z", x, bpm)
rest(0.016, bpm)
keypress("z", x, bpm)
rest(0.018, bpm)
keypress("L", x, bpm)
rest(0.02, bpm)
keypress("l", x, bpm)
rest(0.016, bpm)
keypress("k", x, bpm)
rest(0.018, bpm)
keypress("J", x, bpm)
rest(0.02, bpm)
keypress("j", x, bpm)
rest(0.016, bpm)
keypress("H", x, bpm)
rest(0.018, bpm)
keypress("h", x, bpm)
rest(0.02, bpm)
keypress("G", x, bpm)
rest(0.016, bpm)
keypress("g", x, bpm)
rest(0.018, bpm)
keypress("f", x, bpm)
rest(0.02, bpm)
keypress("D", x, bpm)
rest(0.016, bpm)
keypress("d", x, bpm)
rest(0.018, bpm)
keypress("S", x, bpm)
rest(0.02, bpm)
keypress("s", x, bpm)
rest(0.016, bpm)
keypress("a", x, bpm)
rest(0.018, bpm)
keypress("P", x, bpm)
rest(0.02, bpm)
keypress("p", x, bpm)
rest(0.016, bpm)
keypress("O", x, bpm)
rest(0.018, bpm)
keypress("o", x, bpm)
rest(0.02, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(2.143, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.214, bpm)
keypress("*", x, bpm)
rest(0.214, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.214, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
rest(0.214, bpm)
keypress("*", x, bpm)
rest(0.214, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.214, bpm)
keypress("*", x, bpm)
rest(0.214, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.214, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
rest(0.214, bpm)
keypress("*", x, bpm)
rest(0.214, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.643, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.857, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.857, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.857, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.857, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.857, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.857, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.857, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("Q", x, bpm)
rest(0.429, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("Q", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.214, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("@", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("7", x, bpm)
rest(0.214, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.429, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)

finishedSong()