rest(4, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(1.5, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(2, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("P", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(2, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(1.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(1.5, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(2, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("P", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("i", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(2, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
keypress("@", x, bpm)
rest(2, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(1.5, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(2, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("P", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("i", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(2, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(1.75, bpm)
keypress("@", x, bpm)
rest(0.125, bpm)
keypress("(", x, bpm)
rest(0.125, bpm)
keypress("Q", x, bpm)
rest(0.062, bpm)
keypress("E", x, bpm)
rest(0.062, bpm)
keypress("T", x, bpm)
rest(0.031, bpm)
keypress("I", x, bpm)
rest(1.844, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(1.5, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(2, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(2, bpm)
keypress("P", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("i", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("r", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(1.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("P", x, bpm)
keypress("T", x, bpm)
rest(0.667, bpm)
keypress("k", x, bpm)
keypress("a", x, bpm)
rest(0.667, bpm)
keypress("L", x, bpm)
keypress("S", x, bpm)
rest(0.667, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(2, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(2, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(1.5, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(2, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(2, bpm)
keypress("P", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(2, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(1.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(1.5, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(2, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("P", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(2, bpm)
keypress("r", x, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(2, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
rest(2, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(1.5, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(2, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("T", x, bpm)
keypress("W", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("P", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(2, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(1.667, bpm)
keypress("@", x, bpm)
rest(0.083, bpm)
keypress("Q", x, bpm)
rest(0.083, bpm)
keypress("(", x, bpm)
rest(0.167, bpm)
keypress("E", x, bpm)
rest(0.031, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(1.969, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(1.5, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(2, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(1.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.667, bpm)
keypress("k", x, bpm)
keypress("a", x, bpm)
rest(0.667, bpm)
keypress("L", x, bpm)
keypress("S", x, bpm)
rest(0.667, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(2, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(1.667, bpm)
keypress("(", x, bpm)
rest(0.083, bpm)
keypress("E", x, bpm)
rest(0.083, bpm)
keypress("Q", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(2, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(2, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(1.5, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(2, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("T", x, bpm)
keypress("W", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("P", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(2, bpm)
keypress("r", x, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(2, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(1.5, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(1.5, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(2, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("P", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(1.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("i", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(2, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(2, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(1.5, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(2.25, bpm)
keypress("G", x, bpm)
rest(1.083, bpm)
keypress("D", x, bpm)
rest(1.167, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
rest(0.031, bpm)
keypress("T", x, bpm)
keypress("q", x, bpm)
keypress("^", x, bpm)
rest(1.719, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(2.25, bpm)
keypress("Y", x, bpm)
keypress("Q", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.062, bpm)
keypress("7", x, bpm)
rest(2.438, bpm)
keypress("P", x, bpm)
rest(1.167, bpm)
keypress("a", x, bpm)
rest(1.083, bpm)
keypress("S", x, bpm)
rest(1.75, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(2.5, bpm)
keypress("i", x, bpm)
keypress("r", x, bpm)
rest(0.167, bpm)
keypress("Q", x, bpm)
keypress("%", x, bpm)
rest(0.667, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("Y", x, bpm)
rest(2.333, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.167, bpm)
keypress("q", x, bpm)
rest(4.25, bpm)
keypress("T", x, bpm)
rest(0.417, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(0.167, bpm)
keypress("Q", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)

finishedSong()