keypress("u", x, bpm)
keypress("6", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.167, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.167, bpm)
keypress("e", x, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.167, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.083, bpm)
keypress("I", x, bpm)
rest(0.167, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.375, bpm)
keypress("6", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.375, bpm)
keypress("*", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("6", x, bpm)
rest(0.125, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.167, bpm)
keypress("%", x, bpm)
rest(0.167, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.375, bpm)
keypress("Q", x, bpm)
rest(0.125, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
rest(1.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(1.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("e", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("y", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("r", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.167, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.167, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.167, bpm)
keypress("O", x, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.167, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("W", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("T", x, bpm)
rest(0.1, bpm)
keypress("p", x, bpm)
rest(0.1, bpm)
keypress("O", x, bpm)
rest(0.1, bpm)
keypress("I", x, bpm)
rest(0.033, bpm)
keypress("Y", x, bpm)
rest(0.067, bpm)
keypress("u", x, bpm)
rest(0.1, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.375, bpm)
keypress("*", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
rest(0.096, bpm)
keypress("$", x, bpm)
rest(0.404, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("6", x, bpm)
rest(0.125, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.167, bpm)
keypress("%", x, bpm)
rest(0.167, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.375, bpm)
keypress("Q", x, bpm)
rest(0.125, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
rest(1.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(1.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
rest(0.096, bpm)
keypress("r", x, bpm)
rest(0.404, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("p", x, bpm)
rest(0.096, bpm)
keypress("k", x, bpm)
rest(0.098, bpm)
keypress("x", x, bpm)
rest(0.806, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(0.096, bpm)
keypress("k", x, bpm)
rest(0.098, bpm)
keypress("L", x, bpm)
rest(0.098, bpm)
keypress("C", x, bpm)
rest(0.708, bpm)
keypress("k", x, bpm)
keypress("a", x, bpm)
keypress("O", x, bpm)
rest(0.096, bpm)
keypress("z", x, bpm)
rest(0.098, bpm)
keypress("x", x, bpm)
rest(0.098, bpm)
keypress("V", x, bpm)
rest(0.042, bpm)
keypress("S", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("P", x, bpm)
keypress("O", x, bpm)
rest(0.096, bpm)
keypress("Z", x, bpm)
rest(0.098, bpm)
keypress("x", x, bpm)
rest(0.14, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
rest(0.167, bpm)
keypress("%", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(0.333, bpm)
keypress("D", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.375, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
rest(0.167, bpm)
keypress("I", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(1.5, bpm)
keypress("f", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.167, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
rest(0.417, bpm)
keypress("6", x, bpm)
rest(0.083, bpm)
keypress("S", x, bpm)
rest(0.167, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
rest(0.167, bpm)
keypress("!", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
rest(0.417, bpm)
keypress("*", x, bpm)
rest(0.083, bpm)
keypress("S", x, bpm)
rest(0.167, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("k", x, bpm)
rest(0.167, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("j", x, bpm)
rest(0.417, bpm)
keypress("6", x, bpm)
rest(0.083, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.75, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
rest(0.167, bpm)
keypress("%", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("j", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
rest(0.167, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.083, bpm)
keypress("G", x, bpm)
rest(0.167, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
rest(0.417, bpm)
keypress("6", x, bpm)
rest(0.083, bpm)
keypress("S", x, bpm)
rest(0.167, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
rest(0.167, bpm)
keypress("f", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
rest(0.167, bpm)
keypress("!", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
rest(0.417, bpm)
keypress("*", x, bpm)
rest(0.083, bpm)
keypress("S", x, bpm)
rest(0.167, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("k", x, bpm)
rest(0.167, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("j", x, bpm)
rest(0.417, bpm)
keypress("6", x, bpm)
rest(0.083, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.75, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
rest(0.167, bpm)
keypress("%", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("j", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
rest(0.167, bpm)
keypress("2", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.096, bpm)
keypress("f", x, bpm)
rest(0.098, bpm)
keypress("H", x, bpm)
rest(0.806, bpm)
keypress("s", x, bpm)
rest(0.667, bpm)
keypress("a", x, bpm)
rest(0.667, bpm)
keypress("u", x, bpm)
rest(0.667, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.096, bpm)
keypress("0", x, bpm)
rest(0.904, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("!", x, bpm)
rest(0.096, bpm)
keypress("*", x, bpm)
rest(0.904, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.096, bpm)
keypress("9", x, bpm)
rest(0.904, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("2", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.083, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("x", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.167, bpm)
keypress("z", x, bpm)
keypress("O", x, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("l", x, bpm)
keypress("I", x, bpm)
keypress("t", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
keypress("O", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.167, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.667, bpm)
keypress("O", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.167, bpm)
keypress("O", x, bpm)
rest(0.167, bpm)
keypress("6", x, bpm)
rest(0.167, bpm)
keypress("I", x, bpm)
rest(0.167, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
rest(0.167, bpm)
keypress("p", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.375, bpm)
keypress("6", x, bpm)
rest(0.125, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.167, bpm)
keypress("%", x, bpm)
rest(0.167, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.375, bpm)
keypress("Q", x, bpm)
rest(0.125, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
rest(1.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(1.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
rest(0.096, bpm)
keypress("r", x, bpm)
rest(0.404, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("p", x, bpm)
rest(0.096, bpm)
keypress("k", x, bpm)
rest(0.098, bpm)
keypress("x", x, bpm)
rest(0.806, bpm)
keypress("H", x, bpm)
keypress("O", x, bpm)
rest(0.096, bpm)
keypress("k", x, bpm)
rest(0.098, bpm)
keypress("L", x, bpm)
rest(0.098, bpm)
keypress("C", x, bpm)
rest(0.708, bpm)
keypress("k", x, bpm)
keypress("a", x, bpm)
keypress("O", x, bpm)
rest(0.096, bpm)
keypress("Z", x, bpm)
rest(0.098, bpm)
keypress("x", x, bpm)
rest(0.098, bpm)
keypress("b", x, bpm)
rest(0.042, bpm)
keypress("S", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
rest(0.333, bpm)
keypress("L", x, bpm)
keypress("P", x, bpm)
keypress("O", x, bpm)
rest(0.096, bpm)
keypress("x", x, bpm)
rest(0.098, bpm)
keypress("V", x, bpm)
rest(0.098, bpm)
keypress("n", x, bpm)
rest(0.042, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.063, bpm)
keypress("S", x, bpm)
rest(0.065, bpm)
keypress("f", x, bpm)
rest(0.065, bpm)
keypress("H", x, bpm)
rest(0.808, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
rest(0.167, bpm)
keypress("%", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(0.333, bpm)
keypress("D", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
rest(0.167, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("E", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.031, bpm)
keypress("r", x, bpm)
rest(0.031, bpm)
keypress("T", x, bpm)
rest(0.033, bpm)
keypress("O", x, bpm)
rest(0.031, bpm)
keypress("p", x, bpm)
rest(0.373, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(1.5, bpm)
keypress("f", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.167, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
rest(0.417, bpm)
keypress("6", x, bpm)
rest(0.083, bpm)
keypress("S", x, bpm)
rest(0.167, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
rest(0.167, bpm)
keypress("f", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
rest(0.167, bpm)
keypress("!", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
rest(0.417, bpm)
keypress("*", x, bpm)
rest(0.083, bpm)
keypress("S", x, bpm)
rest(0.167, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("k", x, bpm)
rest(0.167, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("j", x, bpm)
rest(0.417, bpm)
keypress("6", x, bpm)
rest(0.083, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.75, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
rest(0.167, bpm)
keypress("%", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("j", x, bpm)
keypress("@", x, bpm)
rest(0.096, bpm)
keypress("@", x, bpm)
rest(0.904, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("H", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.083, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
rest(0.167, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.083, bpm)
keypress("G", x, bpm)
rest(0.167, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
rest(0.417, bpm)
keypress("6", x, bpm)
rest(0.083, bpm)
keypress("S", x, bpm)
rest(0.167, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
rest(0.167, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
rest(0.167, bpm)
keypress("!", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
rest(0.417, bpm)
keypress("*", x, bpm)
rest(0.083, bpm)
keypress("S", x, bpm)
rest(0.167, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("k", x, bpm)
rest(0.167, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("j", x, bpm)
rest(0.417, bpm)
keypress("6", x, bpm)
rest(0.083, bpm)
keypress("H", x, bpm)
rest(0.167, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.75, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
rest(0.167, bpm)
keypress("%", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("j", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
rest(0.167, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.333, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.096, bpm)
keypress("f", x, bpm)
rest(0.098, bpm)
keypress("H", x, bpm)
rest(0.806, bpm)
keypress("a", x, bpm)
rest(0.667, bpm)
keypress("S", x, bpm)
rest(0.667, bpm)
keypress("D", x, bpm)
rest(0.667, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("S", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.667, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("6", x, bpm)
keypress("(", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.667, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.167, bpm)
keypress("S", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
rest(0.667, bpm)
keypress("D", x, bpm)
rest(0.083, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.667, bpm)
keypress("D", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
rest(0.75, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("7", x, bpm)
rest(0.125, bpm)
keypress("D", x, bpm)
rest(0.125, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("S", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.667, bpm)
keypress("S", x, bpm)
rest(0.333, bpm)
keypress("l", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.167, bpm)
keypress("L", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("6", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.375, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
rest(0.333, bpm)
keypress("H", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.333, bpm)
keypress("S", x, bpm)
keypress("4", x, bpm)
rest(0.75, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("$", x, bpm)
rest(0.01, bpm)
keypress("S", x, bpm)
rest(0.013, bpm)
keypress("H", x, bpm)
rest(1.227, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.01, bpm)
keypress("d", x, bpm)
rest(0.013, bpm)
keypress("j", x, bpm)
rest(0.977, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(1.75, bpm)
keypress("g", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.096, bpm)
keypress("E", x, bpm)
rest(0.237, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("6", x, bpm)
rest(0.031, bpm)
keypress("E", x, bpm)
rest(0.469, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("2", x, bpm)
rest(0.096, bpm)
keypress("9", x, bpm)
rest(0.237, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.031, bpm)
keypress("w", x, bpm)
rest(0.469, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.083, bpm)
keypress("l", x, bpm)
rest(0.167, bpm)
keypress("^", x, bpm)
rest(0.096, bpm)
keypress("^", x, bpm)
rest(0.237, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.167, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("6", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("3", x, bpm)
rest(0.096, bpm)
keypress("0", x, bpm)
rest(0.904, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("8", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("1", x, bpm)
rest(0.333, bpm)
keypress("j", x, bpm)
rest(0.167, bpm)
keypress("7", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
rest(0.083, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("2", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.417, bpm)
keypress("9", x, bpm)
rest(0.083, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.083, bpm)
keypress("j", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("l", x, bpm)
rest(0.167, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
rest(0.083, bpm)
keypress("j", x, bpm)
rest(0.167, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("6", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("7", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
rest(0.083, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
rest(0.083, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("2", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.417, bpm)
keypress("9", x, bpm)
rest(0.083, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.083, bpm)
keypress("l", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.096, bpm)
keypress("g", x, bpm)
rest(0.098, bpm)
keypress("j", x, bpm)
rest(0.14, bpm)
keypress("J", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
rest(0.083, bpm)
keypress("j", x, bpm)
rest(0.167, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("6", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
rest(0.083, bpm)
keypress("j", x, bpm)
rest(0.167, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
rest(0.083, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.083, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.083, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("2", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.417, bpm)
keypress("2", x, bpm)
rest(0.083, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.083, bpm)
keypress("j", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.083, bpm)
keypress("l", x, bpm)
rest(0.167, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
rest(0.417, bpm)
keypress("^", x, bpm)
rest(0.083, bpm)
keypress("j", x, bpm)
rest(0.167, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("6", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
rest(0.333, bpm)
keypress("J", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.167, bpm)
keypress("f", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.096, bpm)
keypress("d", x, bpm)
rest(0.098, bpm)
keypress("g", x, bpm)
rest(0.098, bpm)
keypress("j", x, bpm)
rest(0.708, bpm)
keypress("i", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.667, bpm)
keypress("u", x, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.667, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.667, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.096, bpm)
keypress("p", x, bpm)
rest(0.096, bpm)
keypress("f", x, bpm)
rest(0.808, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.094, bpm)
keypress("j", x, bpm)
rest(0.406, bpm)
keypress("h", x, bpm)

finishedSong()