keypress("6", x, bpm)
rest(0.333, bpm)
keypress("2", x, bpm)
rest(0.333, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("5", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("4", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.667, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("3", x, bpm)
rest(0.333, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("2", x, bpm)
rest(0.333, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("1", x, bpm)
rest(0.333, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("2", x, bpm)
rest(0.333, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("2", x, bpm)
rest(0.333, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("y", x, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("2", x, bpm)
rest(0.333, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("2", x, bpm)
rest(0.333, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("5", x, bpm)
rest(0.333, bpm)
keypress("2", x, bpm)
rest(0.333, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("!", x, bpm)
rest(0.333, bpm)
keypress("2", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.667, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("2", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("2", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("!", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("2", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("2", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("2", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("2", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("!", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.667, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.667, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("5", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.167, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.167, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("!", x, bpm)
rest(0.333, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("1", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("1", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("1", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("!", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("1", x, bpm)
rest(0.333, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("1", x, bpm)
rest(0.333, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("1", x, bpm)
rest(0.333, bpm)
keypress("3", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("!", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("1", x, bpm)
rest(0.333, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("!", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("1", x, bpm)
rest(0.333, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
rest(0.333, bpm)
keypress("!", x, bpm)
rest(0.333, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("Y", x, bpm)
keypress("i", x, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("1", x, bpm)
rest(0.333, bpm)
keypress("2", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("@", x, bpm)
rest(0.333, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("3", x, bpm)
rest(0.333, bpm)
keypress("3", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.667, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.667, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("3", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.667, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("3", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("1", x, bpm)
rest(0.333, bpm)
keypress("3", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.167, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.167, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("3", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.666, bpm)
keypress("q", x, bpm)
rest(0.166, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.166, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.332, bpm)
keypress("3", x, bpm)
rest(0.332, bpm)
keypress("6", x, bpm)
rest(0.664, bpm)
keypress("q", x, bpm)
rest(0.166, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
rest(0.166, bpm)
keypress("4", x, bpm)
rest(0.332, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.331, bpm)
keypress("3", x, bpm)
rest(0.331, bpm)
keypress("6", x, bpm)
rest(0.662, bpm)
keypress("q", x, bpm)
rest(0.165, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.165, bpm)
keypress("4", x, bpm)
rest(0.331, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("0", x, bpm)
rest(0.33, bpm)
keypress("3", x, bpm)
rest(0.33, bpm)
keypress("6", x, bpm)
rest(0.66, bpm)
keypress("0", x, bpm)
rest(0.165, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.165, bpm)
keypress("3", x, bpm)
rest(0.33, bpm)
keypress("Y", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
rest(0.329, bpm)
keypress("4", x, bpm)
rest(0.329, bpm)
keypress("6", x, bpm)
rest(0.658, bpm)
keypress("0", x, bpm)
rest(0.164, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.164, bpm)
keypress("3", x, bpm)
rest(0.329, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.329, bpm)
keypress("4", x, bpm)
rest(0.328, bpm)
keypress("6", x, bpm)
rest(0.656, bpm)
keypress("0", x, bpm)
rest(0.164, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.164, bpm)
keypress("3", x, bpm)
rest(0.328, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
rest(0.328, bpm)
keypress("4", x, bpm)
rest(0.327, bpm)
keypress("6", x, bpm)
rest(0.654, bpm)
keypress("0", x, bpm)
rest(0.164, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.163, bpm)
keypress("3", x, bpm)
rest(0.327, bpm)
keypress("Y", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
rest(0.327, bpm)
keypress("4", x, bpm)
rest(0.326, bpm)
keypress("6", x, bpm)
rest(0.653, bpm)
keypress("w", x, bpm)
rest(0.163, bpm)
keypress("Y", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.163, bpm)
keypress("6", x, bpm)
rest(0.326, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.326, bpm)
keypress("4", x, bpm)
rest(0.326, bpm)
keypress("(", x, bpm)
rest(0.326, bpm)
keypress("@", x, bpm)
rest(0.325, bpm)
keypress("0", x, bpm)
rest(0.163, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.163, bpm)
keypress("3", x, bpm)
rest(0.325, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.325, bpm)
keypress("@", x, bpm)
rest(0.325, bpm)
keypress("6", x, bpm)
rest(0.649, bpm)
keypress("w", x, bpm)
rest(0.162, bpm)
keypress("Y", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.162, bpm)
keypress("6", x, bpm)
rest(0.324, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("Q", x, bpm)
rest(0.324, bpm)
keypress("4", x, bpm)
rest(0.324, bpm)
keypress("(", x, bpm)
rest(0.324, bpm)
keypress("@", x, bpm)
rest(0.323, bpm)
keypress("0", x, bpm)
rest(0.162, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.162, bpm)
keypress("3", x, bpm)
rest(0.323, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.323, bpm)
keypress("@", x, bpm)
rest(0.323, bpm)
keypress("6", x, bpm)
rest(0.645, bpm)
keypress("W", x, bpm)
rest(0.161, bpm)
keypress("u", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.161, bpm)
keypress("%", x, bpm)
rest(0.322, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(0.322, bpm)
keypress("5", x, bpm)
rest(0.322, bpm)
keypress("0", x, bpm)
rest(0.322, bpm)
keypress("3", x, bpm)
rest(0.322, bpm)
keypress("q", x, bpm)
rest(0.161, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
rest(0.161, bpm)
keypress("4", x, bpm)
rest(0.321, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.321, bpm)
keypress("3", x, bpm)
rest(0.321, bpm)
keypress("6", x, bpm)
rest(0.321, bpm)
keypress("6", x, bpm)
rest(0.321, bpm)
keypress("e", x, bpm)
rest(0.16, bpm)
keypress("u", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.16, bpm)
keypress("6", x, bpm)
rest(0.32, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.32, bpm)
keypress("%", x, bpm)
rest(0.32, bpm)
keypress("0", x, bpm)
rest(0.32, bpm)
keypress("3", x, bpm)
rest(0.32, bpm)
keypress("q", x, bpm)
rest(0.16, bpm)
keypress("t", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
rest(0.16, bpm)
keypress("4", x, bpm)
rest(0.319, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.319, bpm)
keypress("3", x, bpm)
rest(0.319, bpm)
keypress("6", x, bpm)
rest(0.638, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.159, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
rest(0.159, bpm)
keypress("q", x, bpm)
rest(0.319, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.318, bpm)
keypress("q", x, bpm)
rest(0.318, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.318, bpm)
keypress("6", x, bpm)
keypress("q", x, bpm)
rest(0.318, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.159, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.159, bpm)
keypress("q", x, bpm)
rest(0.318, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.317, bpm)
keypress("q", x, bpm)
rest(0.317, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.317, bpm)
keypress("6", x, bpm)
keypress("q", x, bpm)
rest(0.317, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.159, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.158, bpm)
keypress("Q", x, bpm)
rest(0.317, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.317, bpm)
keypress("Q", x, bpm)
rest(0.316, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.316, bpm)
keypress("6", x, bpm)
keypress("Q", x, bpm)
rest(0.316, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(0.158, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
rest(0.158, bpm)
keypress("w", x, bpm)
rest(0.316, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(0.316, bpm)
keypress("w", x, bpm)
rest(0.316, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(0.315, bpm)
keypress("6", x, bpm)
keypress("w", x, bpm)
rest(0.631, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("I", x, bpm)
rest(0.315, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
rest(0.315, bpm)
keypress("u", x, bpm)
rest(0.315, bpm)
keypress("T", x, bpm)
rest(0.315, bpm)
keypress("E", x, bpm)
rest(0.314, bpm)
keypress("w", x, bpm)
rest(0.314, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.314, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.628, bpm)
keypress("w", x, bpm)
rest(0.314, bpm)
keypress("E", x, bpm)
rest(0.313, bpm)
keypress("T", x, bpm)
rest(0.313, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("I", x, bpm)
rest(0.313, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
keypress("o", x, bpm)
rest(0.313, bpm)
keypress("u", x, bpm)
rest(0.313, bpm)
keypress("T", x, bpm)
rest(0.313, bpm)
keypress("E", x, bpm)
rest(0.313, bpm)
keypress("w", x, bpm)
rest(0.313, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.313, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.625, bpm)
keypress("w", x, bpm)
rest(0.312, bpm)
keypress("T", x, bpm)
rest(0.312, bpm)
keypress("u", x, bpm)
rest(0.312, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("p", x, bpm)
rest(0.312, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("P", x, bpm)
rest(0.311, bpm)
keypress("o", x, bpm)
rest(0.311, bpm)
keypress("u", x, bpm)
rest(0.311, bpm)
keypress("T", x, bpm)
rest(0.311, bpm)
keypress("E", x, bpm)
rest(0.311, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.311, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.311, bpm)
keypress("w", x, bpm)
rest(0.31, bpm)
keypress("E", x, bpm)
rest(0.31, bpm)
keypress("T", x, bpm)
rest(0.31, bpm)
keypress("u", x, bpm)
rest(0.31, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("p", x, bpm)
rest(0.31, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("P", x, bpm)
rest(0.31, bpm)
keypress("o", x, bpm)
rest(0.31, bpm)
keypress("u", x, bpm)
rest(0.309, bpm)
keypress("T", x, bpm)
rest(0.309, bpm)
keypress("E", x, bpm)
rest(0.309, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.309, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.309, bpm)
keypress("w", x, bpm)
rest(0.309, bpm)
keypress("E", x, bpm)
rest(0.309, bpm)
keypress("T", x, bpm)
rest(0.231, bpm)
keypress("u", x, bpm)
rest(0.231, bpm)
keypress("o", x, bpm)
rest(0.154, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("Z", x, bpm)
rest(0.077, bpm)
keypress("P", x, bpm)
rest(0.231, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("x", x, bpm)
keypress("S", x, bpm)
rest(0.308, bpm)
keypress("s", x, bpm)
rest(0.308, bpm)
keypress("a", x, bpm)
rest(0.308, bpm)
keypress("P", x, bpm)
rest(0.308, bpm)
keypress("p", x, bpm)
rest(0.308, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("Z", x, bpm)
keypress("O", x, bpm)
rest(0.307, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("x", x, bpm)
keypress("o", x, bpm)
rest(0.307, bpm)
keypress("u", x, bpm)
rest(0.307, bpm)
keypress("T", x, bpm)
rest(0.307, bpm)
keypress("E", x, bpm)
rest(0.307, bpm)
keypress("e", x, bpm)
rest(0.307, bpm)
keypress("G", x, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
keypress("W", x, bpm)
rest(0.307, bpm)
keypress("h", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("w", x, bpm)
rest(0.306, bpm)
keypress("0", x, bpm)
rest(0.306, bpm)
keypress("*", x, bpm)
rest(0.306, bpm)
keypress("^", x, bpm)
rest(0.306, bpm)
keypress("6", x, bpm)
rest(0.306, bpm)
keypress("G", x, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
keypress("%", x, bpm)
rest(0.306, bpm)
keypress("h", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("5", x, bpm)
rest(0.306, bpm)
keypress("3", x, bpm)
rest(0.305, bpm)
keypress("!", x, bpm)
rest(0.305, bpm)
keypress("^", x, bpm)
rest(0.305, bpm)
keypress("6", x, bpm)
rest(0.305, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
keypress("3", x, bpm)
rest(0.305, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("v", x, bpm)
keypress("B", x, bpm)
keypress("1", x, bpm)
keypress("6", x, bpm)
rest(0.457, bpm)
keypress("D", x, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
rest(0.457, bpm)
keypress("f", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("3", x, bpm)
keypress("6", x, bpm)
rest(0.301, bpm)
keypress("^", x, bpm)
rest(0.151, bpm)
keypress("G", x, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
rest(0.151, bpm)
keypress("8", x, bpm)
rest(0.301, bpm)
keypress("h", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.298, bpm)
keypress("0", x, bpm)
rest(0.149, bpm)
keypress("G", x, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
rest(0.149, bpm)
keypress("w", x, bpm)
rest(0.298, bpm)
keypress("h", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.294, bpm)
keypress("E", x, bpm)
rest(0.147, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
rest(0.147, bpm)
keypress("t", x, bpm)
rest(0.294, bpm)
keypress("J", x, bpm)
keypress("v", x, bpm)
keypress("B", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.291, bpm)
keypress("u", x, bpm)
rest(0.145, bpm)
keypress("D", x, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
rest(0.145, bpm)
keypress("o", x, bpm)
rest(0.291, bpm)
keypress("f", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.287, bpm)
keypress("P", x, bpm)
rest(0.144, bpm)
keypress("G", x, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
rest(0.144, bpm)
keypress("s", x, bpm)
rest(0.287, bpm)
keypress("h", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
rest(0.284, bpm)
keypress("f", x, bpm)
rest(0.142, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
rest(0.142, bpm)
keypress("G", x, bpm)
rest(0.284, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("h", x, bpm)
rest(0.213, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("B", x, bpm)
rest(0.206, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("h", x, bpm)
rest(0.206, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("b", x, bpm)
rest(0.206, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.206, bpm)
keypress("C", x, bpm)
rest(0.206, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.206, bpm)
keypress("c", x, bpm)
rest(0.206, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("h", x, bpm)
rest(0.206, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("B", x, bpm)
rest(0.206, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("h", x, bpm)
rest(0.206, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("b", x, bpm)
rest(0.206, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.206, bpm)
keypress("c", x, bpm)
rest(0.206, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.206, bpm)
keypress("x", x, bpm)
rest(0.206, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("h", x, bpm)
rest(0.206, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("B", x, bpm)
rest(0.206, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("h", x, bpm)
rest(0.206, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("b", x, bpm)
rest(0.206, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.206, bpm)
keypress("x", x, bpm)
rest(0.206, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.206, bpm)
keypress("Z", x, bpm)
rest(0.206, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.206, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("b", x, bpm)
rest(0.206, bpm)
keypress("O", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.206, bpm)
keypress("H", x, bpm)
keypress("z", x, bpm)
keypress("V", x, bpm)
rest(0.206, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.206, bpm)
keypress("z", x, bpm)
rest(0.206, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.206, bpm)
keypress("L", x, bpm)
rest(0.206, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
rest(0.206, bpm)
keypress("g", x, bpm)
keypress("L", x, bpm)
keypress("c", x, bpm)
rest(0.206, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
rest(0.206, bpm)
keypress("f", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
rest(0.206, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
rest(0.206, bpm)
keypress("J", x, bpm)
rest(0.206, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
rest(0.206, bpm)
keypress("j", x, bpm)
rest(0.206, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.206, bpm)
keypress("g", x, bpm)
keypress("L", x, bpm)
keypress("c", x, bpm)
rest(0.206, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.206, bpm)
keypress("f", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
rest(0.206, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
rest(0.206, bpm)
keypress("j", x, bpm)
rest(0.206, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.206, bpm)
keypress("H", x, bpm)
rest(0.206, bpm)
keypress("i", x, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
rest(0.206, bpm)
keypress("g", x, bpm)
keypress("L", x, bpm)
keypress("c", x, bpm)
rest(0.206, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
rest(0.206, bpm)
keypress("f", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
rest(0.206, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.206, bpm)
keypress("H", x, bpm)
rest(0.206, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.206, bpm)
keypress("h", x, bpm)
rest(0.206, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.206, bpm)
keypress("d", x, bpm)
keypress("H", x, bpm)
keypress("z", x, bpm)
rest(0.206, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.206, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
rest(0.206, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
rest(0.206, bpm)
keypress("g", x, bpm)
rest(0.206, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.206, bpm)
keypress("f", x, bpm)
rest(0.206, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.206, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
rest(0.208, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.208, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("j", x, bpm)
rest(0.208, bpm)
keypress("9", x, bpm)
keypress("y", x, bpm)
rest(0.208, bpm)
keypress("d", x, bpm)
rest(0.211, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(0.211, bpm)
keypress("S", x, bpm)
rest(0.211, bpm)
keypress("E", x, bpm)
rest(0.211, bpm)
keypress("P", x, bpm)
rest(0.213, bpm)
keypress("e", x, bpm)
rest(0.213, bpm)
keypress("p", x, bpm)
rest(0.213, bpm)
keypress("4", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.213, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.216, bpm)
keypress("3", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.216, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.216, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.216, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.218, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.218, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.218, bpm)
keypress("^", x, bpm)
rest(0.218, bpm)
keypress("E", x, bpm)
rest(0.221, bpm)
keypress("6", x, bpm)
rest(0.221, bpm)
keypress("e", x, bpm)
rest(0.221, bpm)
keypress("3", x, bpm)
rest(0.221, bpm)
keypress("0", x, bpm)
rest(0.223, bpm)
keypress("2", x, bpm)
rest(0.223, bpm)
keypress("9", x, bpm)
rest(0.223, bpm)
keypress("4", x, bpm)
rest(0.223, bpm)
keypress("4", x, bpm)
rest(0.226, bpm)
keypress("3", x, bpm)
rest(0.226, bpm)
keypress("3", x, bpm)
rest(0.226, bpm)
keypress("1", x, bpm)
keypress("6", x, bpm)
rest(0.649, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.507, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.514, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.521, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.536, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.543, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.551, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
rest(0.56, bpm)
keypress("j", x, bpm)
keypress("x", x, bpm)
keypress("S", x, bpm)
rest(0.586, bpm)
keypress("f", x, bpm)
keypress("z", x, bpm)
keypress("x", x, bpm)
keypress("W", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
rest(0.605, bpm)
keypress("h", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("b", x, bpm)
keypress("w", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.625, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.67, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.721, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.721, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.625, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.625, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.625, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("x", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.625, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.625, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
rest(0.625, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.625, bpm)
keypress("S", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.625, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.625, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
rest(0.625, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
rest(0.625, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("x", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.625, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.625, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
rest(0.625, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.625, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("x", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
rest(0.625, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.625, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
rest(0.625, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.625, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("x", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
rest(0.625, bpm)
keypress("g", x, bpm)
keypress("k", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.625, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
rest(0.625, bpm)
keypress("i", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.625, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
keypress("k", x, bpm)
keypress("z", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.625, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.625, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.625, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.625, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
keypress("k", x, bpm)
keypress("z", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.625, bpm)
keypress("S", x, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.625, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.625, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.625, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.625, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.625, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
rest(0.625, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.625, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
rest(0.625, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.625, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("x", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.625, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.625, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
rest(0.625, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
rest(0.625, bpm)
keypress("S", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("T", x, bpm)
rest(0.625, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.625, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
rest(0.625, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.625, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("x", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
rest(0.625, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.625, bpm)
keypress("G", x, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.625, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
keypress("v", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.625, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
keypress("9", x, bpm)
keypress("0", x, bpm)
rest(0.625, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.625, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.625, bpm)
keypress("f", x, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
keypress("x", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
rest(0.625, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("J", x, bpm)
keypress("5", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.625, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("k", x, bpm)
keypress("%", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.625, bpm)
keypress("d", x, bpm)
keypress("k", x, bpm)
keypress("z", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
rest(0.625, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.625, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(0.625, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.625, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.625, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
rest(0.625, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
rest(0.625, bpm)
keypress("S", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("u", x, bpm)
rest(0.625, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
keypress("q", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.625, bpm)
keypress("S", x, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.625, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
keypress("k", x, bpm)
keypress("z", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.625, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.625, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(0.625, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.625, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.625, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.625, bpm)
keypress("j", x, bpm)
keypress("p", x, bpm)
rest(0.625, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.625, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
rest(0.625, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(0.625, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.625, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.625, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
rest(0.625, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.625, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.625, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.625, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
rest(0.625, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.625, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.625, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("w", x, bpm)
rest(0.625, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.625, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.625, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.625, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(0.625, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.625, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.625, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(0.625, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
rest(0.625, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
keypress("9", x, bpm)
keypress("0", x, bpm)
rest(0.625, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.625, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
rest(0.625, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.625, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
rest(0.625, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
rest(0.625, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("J", x, bpm)
keypress("5", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.625, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.625, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.625, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.625, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.625, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.625, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.625, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
keypress("y", x, bpm)
rest(0.625, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.625, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.625, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(0.625, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(0.625, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("c", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.625, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.625, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.625, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.625, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.625, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
keypress("v", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.625, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.625, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.625, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.625, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.625, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("q", x, bpm)
rest(0.625, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.625, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.625, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.625, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(0.625, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
rest(0.625, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.625, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.625, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.625, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
rest(0.625, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.625, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
keypress("b", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.625, bpm)
keypress("r", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(0.625, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("3", x, bpm)
keypress("6", x, bpm)
rest(0.625, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
rest(0.625, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("b", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("p", x, bpm)
rest(0.625, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(0.629, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("e", x, bpm)
rest(0.633, bpm)
keypress("H", x, bpm)
keypress("l", x, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.637, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
keypress("b", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.641, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("$", x, bpm)
rest(0.645, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.649, bpm)
keypress("H", x, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.653, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
keypress("b", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.658, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.662, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.667, bpm)
keypress("H", x, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
keypress("V", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.671, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("c", x, bpm)
keypress("b", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.676, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("@", x, bpm)
rest(0.68, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.457, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("c", x, bpm)
keypress("V", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.459, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("c", x, bpm)
keypress("b", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.461, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
keypress("6", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("6", x, bpm)
rest(0.694, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("2", x, bpm)
rest(0.694, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.694, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.694, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
keypress("Q", x, bpm)
rest(0.694, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.694, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
keypress("y", x, bpm)
rest(0.694, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("E", x, bpm)
keypress("I", x, bpm)
rest(0.694, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.694, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
keypress("m", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("s", x, bpm)
rest(0.694, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.694, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.694, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.694, bpm)
keypress("h", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("w", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.694, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.694, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("v", x, bpm)
keypress("B", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.694, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.694, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("2", x, bpm)
rest(0.694, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.694, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
rest(0.694, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
keypress("Q", x, bpm)
rest(0.694, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.694, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
keypress("y", x, bpm)
rest(0.694, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("E", x, bpm)
keypress("I", x, bpm)
rest(0.694, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.694, bpm)
keypress("l", x, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
keypress("m", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("s", x, bpm)
rest(0.694, bpm)
keypress("J", x, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.694, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.694, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.463, bpm)
keypress("h", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("w", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.463, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.463, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.463, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.463, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("v", x, bpm)
keypress("B", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.463, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.694, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.694, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.694, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.694, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.463, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.463, bpm)
keypress("H", x, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.463, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.463, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.463, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("v", x, bpm)
keypress("B", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.463, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.694, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.694, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.463, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.463, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.463, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.463, bpm)
keypress("h", x, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.463, bpm)
keypress("H", x, bpm)
keypress("l", x, bpm)
keypress("x", x, bpm)
keypress("V", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.463, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("c", x, bpm)
keypress("V", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.347, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("c", x, bpm)
keypress("b", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.347, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.347, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("v", x, bpm)
keypress("B", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.347, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.463, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
rest(0.463, bpm)
keypress("s", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.463, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.463, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.463, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("Z", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("Y", x, bpm)
rest(0.463, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.463, bpm)
keypress("I", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.463, bpm)
keypress("o", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("w", x, bpm)
rest(0.463, bpm)
keypress("O", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
rest(0.463, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.463, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.463, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.463, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.463, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.463, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.463, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.463, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.463, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.463, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.463, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.463, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.463, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
rest(0.463, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.463, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.417, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.411, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.406, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(0.4, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.395, bpm)
keypress("9", x, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(0.39, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(0.385, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(0.38, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.375, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.37, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(0.366, bpm)
keypress("9", x, bpm)
keypress("2", x, bpm)
rest(0.362, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.357, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.353, bpm)
keypress("(", x, bpm)
keypress("@", x, bpm)
rest(0.349, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.345, bpm)
keypress("9", x, bpm)
keypress("2", x, bpm)
rest(0.341, bpm)
keypress("(", x, bpm)
keypress("@", x, bpm)
rest(0.337, bpm)
keypress("^", x, bpm)
rest(0.333, bpm)
keypress("9", x, bpm)
keypress("2", x, bpm)
rest(0.33, bpm)
keypress("6", x, bpm)
rest(0.326, bpm)
keypress("^", x, bpm)
rest(0.323, bpm)
keypress("$", x, bpm)
rest(0.319, bpm)
keypress("6", x, bpm)
rest(0.316, bpm)
keypress("2", x, bpm)
rest(0.234, bpm)
keypress("6", x, bpm)
rest(0.078, bpm)
keypress("2", x, bpm)
rest(0.156, bpm)
keypress("9", x, bpm)
rest(0.156, bpm)
keypress("2", x, bpm)
rest(0.078, bpm)
keypress("Q", x, bpm)
rest(0.234, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(0.234, bpm)
keypress("Q", x, bpm)
rest(0.234, bpm)
keypress("9", x, bpm)
rest(0.234, bpm)
keypress("6", x, bpm)
rest(0.234, bpm)
keypress("2", x, bpm)
rest(0.234, bpm)
keypress("Q", x, bpm)
rest(0.078, bpm)
keypress("6", x, bpm)
rest(0.156, bpm)
keypress("e", x, bpm)
rest(0.156, bpm)
keypress("9", x, bpm)
rest(0.078, bpm)
keypress("y", x, bpm)
rest(0.234, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
rest(0.234, bpm)
keypress("y", x, bpm)
rest(0.234, bpm)
keypress("e", x, bpm)
rest(0.234, bpm)
keypress("Q", x, bpm)
rest(0.234, bpm)
keypress("6", x, bpm)
rest(0.234, bpm)
keypress("e", x, bpm)
rest(0.078, bpm)
keypress("9", x, bpm)
rest(0.156, bpm)
keypress("y", x, bpm)
rest(0.156, bpm)
keypress("Q", x, bpm)
rest(0.078, bpm)
keypress("I", x, bpm)
rest(0.234, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.234, bpm)
keypress("I", x, bpm)
rest(0.234, bpm)
keypress("y", x, bpm)
rest(0.234, bpm)
keypress("e", x, bpm)
rest(0.234, bpm)
keypress("9", x, bpm)
rest(0.234, bpm)
keypress("I", x, bpm)
rest(0.078, bpm)
keypress("e", x, bpm)
rest(0.156, bpm)
keypress("p", x, bpm)
rest(0.156, bpm)
keypress("y", x, bpm)
rest(0.078, bpm)
keypress("d", x, bpm)
rest(0.234, bpm)
keypress("j", x, bpm)
keypress("I", x, bpm)
rest(0.234, bpm)
keypress("d", x, bpm)
rest(0.234, bpm)
keypress("p", x, bpm)
rest(0.234, bpm)
keypress("I", x, bpm)
rest(0.234, bpm)
keypress("e", x, bpm)
rest(0.234, bpm)
keypress("p", x, bpm)
rest(0.078, bpm)
keypress("y", x, bpm)
rest(0.156, bpm)
keypress("d", x, bpm)
rest(0.156, bpm)
keypress("I", x, bpm)
rest(0.078, bpm)
keypress("G", x, bpm)
rest(0.234, bpm)
keypress("z", x, bpm)
keypress("d", x, bpm)
rest(0.234, bpm)
keypress("G", x, bpm)
rest(0.234, bpm)
keypress("d", x, bpm)
rest(0.234, bpm)
keypress("p", x, bpm)
rest(0.234, bpm)
keypress("y", x, bpm)
rest(0.234, bpm)
keypress("G", x, bpm)
rest(0.078, bpm)
keypress("p", x, bpm)
rest(0.156, bpm)
keypress("j", x, bpm)
rest(0.156, bpm)
keypress("d", x, bpm)
rest(0.078, bpm)
keypress("z", x, bpm)
rest(0.234, bpm)
keypress("b", x, bpm)
keypress("G", x, bpm)
rest(0.234, bpm)
keypress("z", x, bpm)
rest(0.234, bpm)
keypress("j", x, bpm)
rest(0.234, bpm)
keypress("G", x, bpm)
rest(0.234, bpm)
keypress("p", x, bpm)
rest(0.234, bpm)
keypress("j", x, bpm)
rest(0.078, bpm)
keypress("d", x, bpm)
rest(0.156, bpm)
keypress("z", x, bpm)
rest(0.156, bpm)
keypress("G", x, bpm)
rest(0.078, bpm)
keypress("C", x, bpm)
rest(0.234, bpm)
keypress("z", x, bpm)
rest(0.234, bpm)
keypress("C", x, bpm)
rest(0.234, bpm)
keypress("z", x, bpm)
rest(0.234, bpm)
keypress("j", x, bpm)
rest(0.234, bpm)
keypress("p", x, bpm)
rest(0.234, bpm)
keypress("j", x, bpm)
rest(0.078, bpm)
keypress("d", x, bpm)
rest(0.156, bpm)
keypress("z", x, bpm)
rest(0.156, bpm)
keypress("G", x, bpm)
rest(0.078, bpm)
keypress("C", x, bpm)
rest(0.234, bpm)
keypress("z", x, bpm)
rest(0.234, bpm)
keypress("C", x, bpm)
rest(0.234, bpm)
keypress("z", x, bpm)
rest(0.234, bpm)
keypress("j", x, bpm)
rest(0.234, bpm)
keypress("y", x, bpm)
rest(0.234, bpm)
keypress("p", x, bpm)
rest(0.234, bpm)
keypress("d", x, bpm)
rest(0.234, bpm)
keypress("h", x, bpm)
rest(0.234, bpm)
keypress("j", x, bpm)
rest(0.234, bpm)
keypress("G", x, bpm)
rest(0.234, bpm)
keypress("d", x, bpm)
rest(0.234, bpm)
keypress("P", x, bpm)
rest(0.234, bpm)
keypress("p", x, bpm)
rest(0.234, bpm)
keypress("G", x, bpm)
rest(0.234, bpm)
keypress("j", x, bpm)
rest(0.234, bpm)
keypress("z", x, bpm)
rest(0.234, bpm)
keypress("b", x, bpm)
rest(0.234, bpm)
keypress("Z", x, bpm)
rest(0.234, bpm)
keypress("z", x, bpm)
rest(0.234, bpm)
keypress("j", x, bpm)
keypress("Y", x, bpm)
rest(0.234, bpm)
keypress("y", x, bpm)
rest(0.234, bpm)
keypress("p", x, bpm)
rest(0.234, bpm)
keypress("d", x, bpm)
rest(0.234, bpm)
keypress("h", x, bpm)
rest(0.234, bpm)
keypress("j", x, bpm)
rest(0.234, bpm)
keypress("G", x, bpm)
rest(0.234, bpm)
keypress("d", x, bpm)
rest(0.234, bpm)
keypress("P", x, bpm)
rest(0.234, bpm)
keypress("p", x, bpm)
rest(0.234, bpm)
keypress("G", x, bpm)
rest(0.234, bpm)
keypress("j", x, bpm)
rest(0.234, bpm)
keypress("z", x, bpm)
rest(0.234, bpm)
keypress("b", x, bpm)
rest(0.234, bpm)
keypress("Z", x, bpm)
rest(0.234, bpm)
keypress("z", x, bpm)
rest(0.234, bpm)
keypress("j", x, bpm)
keypress("Y", x, bpm)
rest(0.234, bpm)
keypress("y", x, bpm)
rest(0.234, bpm)
keypress("p", x, bpm)
rest(0.234, bpm)
keypress("d", x, bpm)
rest(0.234, bpm)
keypress("h", x, bpm)
rest(0.234, bpm)
keypress("j", x, bpm)
rest(0.234, bpm)
keypress("G", x, bpm)
rest(0.234, bpm)
keypress("d", x, bpm)
rest(0.234, bpm)
keypress("P", x, bpm)
rest(0.234, bpm)
keypress("p", x, bpm)
rest(0.207, bpm)
keypress("G", x, bpm)
rest(0.211, bpm)
keypress("j", x, bpm)
rest(0.207, bpm)
keypress("z", x, bpm)
rest(0.207, bpm)
keypress("C", x, bpm)
rest(0.211, bpm)
keypress("z", x, bpm)
rest(0.207, bpm)
keypress("B", x, bpm)
rest(0.207, bpm)
keypress("b", x, bpm)
rest(0.184, bpm)
keypress("Y", x, bpm)
rest(0.027, bpm)
keypress("z", x, bpm)
rest(0.207, bpm)
keypress("y", x, bpm)
rest(0.234, bpm)
keypress("p", x, bpm)
rest(0.234, bpm)
keypress("d", x, bpm)
rest(0.234, bpm)
keypress("h", x, bpm)
rest(0.234, bpm)
keypress("j", x, bpm)
rest(0.234, bpm)
keypress("G", x, bpm)
rest(0.234, bpm)
keypress("d", x, bpm)
rest(0.234, bpm)
keypress("P", x, bpm)
rest(0.234, bpm)
keypress("p", x, bpm)
rest(0.207, bpm)
keypress("G", x, bpm)
rest(0.211, bpm)
keypress("j", x, bpm)
rest(0.207, bpm)
keypress("l", x, bpm)
rest(0.207, bpm)
keypress("z", x, bpm)
rest(0.211, bpm)
keypress("m", x, bpm)
rest(0.207, bpm)
keypress("v", x, bpm)
rest(0.207, bpm)
keypress("C", x, bpm)
rest(0.184, bpm)
keypress("Y", x, bpm)
rest(0.027, bpm)
keypress("l", x, bpm)

finishedSong()