keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("Q", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.75, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.75, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("t", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.75, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.75, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("t", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("t", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("u", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.75, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.75, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)

finishedSong()