rest(2, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(1.5, bpm)
keypress("P", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(3, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(4, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
rest(1.5, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(1.5, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
rest(1.5, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(2, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(2, bpm)
keypress("G", x, bpm)
keypress("E", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
rest(1.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("i", x, bpm)
rest(1.5, bpm)
keypress("g", x, bpm)
rest(1.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("S", x, bpm)
rest(1.5, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(1.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("%", x, bpm)
rest(1.5, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(3.5, bpm)
keypress("B", x, bpm)
keypress("I", x, bpm)
rest(0.625, bpm)
keypress("V", x, bpm)
keypress("P", x, bpm)
rest(0.625, bpm)
keypress("c", x, bpm)
keypress("S", x, bpm)
rest(0.625, bpm)
keypress("c", x, bpm)
rest(1.25, bpm)
keypress("Z", x, bpm)
rest(0.625, bpm)
keypress("c", x, bpm)
keypress("P", x, bpm)
rest(0.625, bpm)
keypress("S", x, bpm)
rest(0.625, bpm)
keypress("L", x, bpm)
keypress("g", x, bpm)
rest(0.625, bpm)
keypress("L", x, bpm)
rest(1.875, bpm)
keypress("B", x, bpm)
keypress("T", x, bpm)
rest(0.625, bpm)
keypress("V", x, bpm)
keypress("i", x, bpm)
rest(0.625, bpm)
keypress("c", x, bpm)
keypress("O", x, bpm)
rest(0.625, bpm)
keypress("c", x, bpm)
rest(1.25, bpm)
keypress("Z", x, bpm)
rest(0.625, bpm)
keypress("Z", x, bpm)
keypress("O", x, bpm)
rest(0.625, bpm)
keypress("s", x, bpm)
rest(0.625, bpm)
keypress("L", x, bpm)
keypress("D", x, bpm)
rest(0.625, bpm)
keypress("Z", x, bpm)
rest(1.25, bpm)
keypress("L", x, bpm)
rest(0.625, bpm)
keypress("J", x, bpm)
keypress("I", x, bpm)
rest(0.625, bpm)
keypress("L", x, bpm)
keypress("P", x, bpm)
rest(0.625, bpm)
keypress("Z", x, bpm)
keypress("S", x, bpm)
rest(0.625, bpm)
keypress("c", x, bpm)
rest(0.625, bpm)
keypress("Z", x, bpm)
rest(0.625, bpm)
keypress("L", x, bpm)
rest(0.625, bpm)
keypress("c", x, bpm)
keypress("P", x, bpm)
rest(0.625, bpm)
keypress("S", x, bpm)
rest(0.625, bpm)
keypress("g", x, bpm)
rest(2.5, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
rest(0.625, bpm)
keypress("L", x, bpm)
keypress("i", x, bpm)
rest(0.625, bpm)
keypress("Z", x, bpm)
keypress("O", x, bpm)
rest(0.625, bpm)
keypress("c", x, bpm)
rest(0.625, bpm)
keypress("Z", x, bpm)
rest(0.625, bpm)
keypress("L", x, bpm)
rest(0.625, bpm)
keypress("Z", x, bpm)
keypress("W", x, bpm)
rest(0.107, bpm)
keypress("t", x, bpm)
rest(0.112, bpm)
keypress("Y", x, bpm)
rest(0.112, bpm)
keypress("O", x, bpm)
rest(0.294, bpm)
keypress("L", x, bpm)
rest(0.625, bpm)
keypress("l", x, bpm)

finishedSong()