keypress("6", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.667, bpm)
keypress("o", x, bpm)
rest(0.333, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("r", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.667, bpm)
keypress("i", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.667, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
rest(0.667, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("1", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("9", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.667, bpm)
keypress("o", x, bpm)
rest(0.333, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("r", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.667, bpm)
keypress("i", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.667, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
rest(0.667, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("1", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("6", x, bpm)
rest(0.667, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("o", x, bpm)
rest(0.667, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("q", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("5", x, bpm)
rest(0.667, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
rest(0.667, bpm)
keypress("u", x, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("1", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.667, bpm)
keypress("o", x, bpm)
rest(0.333, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("r", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.667, bpm)
keypress("i", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.667, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
rest(0.667, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("1", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("6", x, bpm)
rest(0.667, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("o", x, bpm)
rest(0.667, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("q", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("5", x, bpm)
rest(0.667, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
rest(0.667, bpm)
keypress("u", x, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("1", x, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.667, bpm)
keypress("h", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("a", x, bpm)
rest(0.333, bpm)
keypress("g", x, bpm)
rest(0.667, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.667, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
rest(0.667, bpm)
keypress("p", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("1", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(2, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)

finishedSong()