rest(2, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
rest(2, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("S", x, bpm)
keypress("D", x, bpm)
keypress("e", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(4, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("k", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("%", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("p", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.083, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.333, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(2, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(2, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(2.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
rest(2, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("D", x, bpm)
keypress("e", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)

finishedSong()