keypress("r", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("y", x, bpm)
rest(0.754, bpm)
keypress("t", x, bpm)
rest(0.515, bpm)
keypress("r", x, bpm)
rest(0.532, bpm)
keypress("0", x, bpm)
rest(0.561, bpm)
keypress("0", x, bpm)
rest(0.607, bpm)
keypress("r", x, bpm)
rest(0.678, bpm)
keypress("0", x, bpm)
rest(0.398, bpm)
keypress("0", x, bpm)
rest(0.443, bpm)
keypress("0", x, bpm)
rest(0.506, bpm)
keypress("0", x, bpm)
rest(0.6, bpm)
keypress("r", x, bpm)
rest(1.5, bpm)
keypress("5", x, bpm)
rest(0.032, bpm)
keypress("%", x, bpm)
rest(0.037, bpm)
keypress("6", x, bpm)
rest(0.042, bpm)
keypress("^", x, bpm)
rest(0.032, bpm)
keypress("7", x, bpm)
rest(0.037, bpm)
keypress("1", x, bpm)
rest(0.042, bpm)
keypress("!", x, bpm)
rest(0.032, bpm)
keypress("2", x, bpm)
rest(0.037, bpm)
keypress("@", x, bpm)
rest(0.042, bpm)
keypress("3", x, bpm)
rest(0.032, bpm)
keypress("4", x, bpm)
rest(0.037, bpm)
keypress("$", x, bpm)
rest(0.042, bpm)
keypress("5", x, bpm)
rest(0.032, bpm)
keypress("%", x, bpm)
rest(0.037, bpm)
keypress("6", x, bpm)
rest(0.042, bpm)
keypress("^", x, bpm)
rest(0.032, bpm)
keypress("7", x, bpm)
rest(0.037, bpm)
keypress("8", x, bpm)
rest(0.042, bpm)
keypress("*", x, bpm)
rest(0.032, bpm)
keypress("9", x, bpm)
rest(0.037, bpm)
keypress("(", x, bpm)
rest(0.042, bpm)
keypress("0", x, bpm)
rest(0.032, bpm)
keypress("q", x, bpm)
rest(0.037, bpm)
keypress("Q", x, bpm)
rest(0.042, bpm)
keypress("w", x, bpm)
rest(0.032, bpm)
keypress("W", x, bpm)
rest(0.037, bpm)
keypress("e", x, bpm)
rest(0.042, bpm)
keypress("E", x, bpm)
rest(0.111, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
rest(0.059, bpm)
keypress("0", x, bpm)
rest(0.066, bpm)
keypress("w", x, bpm)
rest(0.072, bpm)
keypress("r", x, bpm)
rest(1.303, bpm)
keypress("a", x, bpm)
rest(1.5, bpm)
keypress("a", x, bpm)
rest(1.125, bpm)
keypress("d", x, bpm)
rest(1.125, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(0.059, bpm)
keypress("8", x, bpm)
rest(0.066, bpm)
keypress("0", x, bpm)
rest(0.072, bpm)
keypress("e", x, bpm)
rest(1.303, bpm)
keypress("a", x, bpm)
rest(0.75, bpm)
keypress("I", x, bpm)
rest(0.375, bpm)
keypress("I", x, bpm)
rest(0.375, bpm)
keypress("a", x, bpm)
rest(1.125, bpm)
keypress("d", x, bpm)
rest(1.125, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.028, bpm)
keypress("%", x, bpm)
rest(0.038, bpm)
keypress("7", x, bpm)
rest(0.034, bpm)
keypress("0", x, bpm)
rest(1.4, bpm)
keypress("a", x, bpm)
rest(1.5, bpm)
keypress("a", x, bpm)
rest(1.125, bpm)
keypress("d", x, bpm)
rest(1.125, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("a", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("a", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.375, bpm)
keypress("u", x, bpm)
rest(0.375, bpm)
keypress("u", x, bpm)
rest(0.375, bpm)
keypress("u", x, bpm)
rest(0.375, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.375, bpm)
keypress("a", x, bpm)
rest(0.375, bpm)
keypress("a", x, bpm)
rest(0.75, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
rest(0.059, bpm)
keypress("0", x, bpm)
rest(0.066, bpm)
keypress("w", x, bpm)
rest(0.072, bpm)
keypress("r", x, bpm)
rest(1.303, bpm)
keypress("a", x, bpm)
rest(1.5, bpm)
keypress("a", x, bpm)
rest(1.125, bpm)
keypress("d", x, bpm)
rest(1.125, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(0.059, bpm)
keypress("8", x, bpm)
rest(0.066, bpm)
keypress("0", x, bpm)
rest(0.072, bpm)
keypress("e", x, bpm)
rest(1.303, bpm)
keypress("a", x, bpm)
rest(0.75, bpm)
keypress("I", x, bpm)
rest(0.375, bpm)
keypress("I", x, bpm)
rest(0.375, bpm)
keypress("a", x, bpm)
rest(1.125, bpm)
keypress("d", x, bpm)
rest(1.125, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.028, bpm)
keypress("%", x, bpm)
rest(0.038, bpm)
keypress("7", x, bpm)
rest(0.034, bpm)
keypress("0", x, bpm)
rest(1.4, bpm)
keypress("a", x, bpm)
rest(1.5, bpm)
keypress("a", x, bpm)
rest(1.125, bpm)
keypress("d", x, bpm)
rest(1.125, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("a", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
rest(0.776, bpm)
keypress("u", x, bpm)
rest(0.823, bpm)
keypress("a", x, bpm)
rest(0.89, bpm)
keypress("u", x, bpm)
rest(0.491, bpm)
keypress("u", x, bpm)
rest(0.52, bpm)
keypress("u", x, bpm)
rest(0.554, bpm)
keypress("u", x, bpm)
rest(0.594, bpm)
keypress("a", x, bpm)
rest(0.644, bpm)
keypress("a", x, bpm)
rest(0.703, bpm)
keypress("a", x, bpm)
rest(1.554, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.667, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.667, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.667, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.667, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.667, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.333, bpm)
keypress("d", x, bpm)
rest(0.333, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.667, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.667, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.667, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.667, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.667, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("I", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.667, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("d", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.667, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.667, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.667, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.667, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.667, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.667, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.667, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("d", x, bpm)
rest(0.333, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.667, bpm)
keypress("s", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.667, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.667, bpm)
keypress("u", x, bpm)
rest(0.667, bpm)
keypress("u", x, bpm)
rest(0.667, bpm)
keypress("a", x, bpm)
rest(0.667, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.025, bpm)
keypress("1", x, bpm)
rest(0.028, bpm)
keypress("!", x, bpm)
rest(0.031, bpm)
keypress("2", x, bpm)
rest(0.025, bpm)
keypress("@", x, bpm)
rest(0.028, bpm)
keypress("3", x, bpm)
rest(0.031, bpm)
keypress("4", x, bpm)
rest(0.025, bpm)
keypress("$", x, bpm)
rest(0.028, bpm)
keypress("5", x, bpm)
rest(0.031, bpm)
keypress("%", x, bpm)
rest(0.025, bpm)
keypress("6", x, bpm)
rest(0.028, bpm)
keypress("^", x, bpm)
rest(0.031, bpm)
keypress("7", x, bpm)
rest(0.025, bpm)
keypress("8", x, bpm)
rest(0.028, bpm)
keypress("*", x, bpm)
rest(0.031, bpm)
keypress("9", x, bpm)
rest(0.025, bpm)
keypress("(", x, bpm)
rest(0.028, bpm)
keypress("0", x, bpm)
rest(0.031, bpm)
keypress("q", x, bpm)
rest(0.025, bpm)
keypress("Q", x, bpm)
rest(0.028, bpm)
keypress("w", x, bpm)
rest(0.031, bpm)
keypress("W", x, bpm)
rest(0.025, bpm)
keypress("e", x, bpm)
rest(0.028, bpm)
keypress("E", x, bpm)
rest(0.031, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.632, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.632, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.632, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.632, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.632, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.316, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
rest(0.316, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.632, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.632, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.632, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.632, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.632, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.316, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.316, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.632, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.316, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
rest(0.316, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.632, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.632, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.632, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.632, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.632, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.632, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.632, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.316, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
rest(0.316, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.632, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.632, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.632, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.632, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.632, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.632, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.316, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.316, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.316, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.316, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.316, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.316, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.632, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.632, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.632, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.632, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.632, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.632, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.316, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
rest(0.316, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.632, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.632, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.632, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.632, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.632, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.316, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.316, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.632, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.316, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
rest(0.316, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.632, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.632, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.632, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.632, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.632, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.632, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.632, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.316, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
rest(0.316, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.632, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.632, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.632, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.635, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.651, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.688, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.379, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.405, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.442, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.493, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.568, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.686, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(1.786, bpm)
keypress("k", x, bpm)
keypress("8", x, bpm)
rest(0.063, bpm)
keypress("0", x, bpm)
rest(0.063, bpm)
keypress("w", x, bpm)
rest(0.07, bpm)
keypress("r", x, bpm)
rest(1.403, bpm)
keypress("k", x, bpm)
rest(1.6, bpm)
keypress("k", x, bpm)
rest(1.2, bpm)
keypress("z", x, bpm)
rest(1.2, bpm)
keypress("l", x, bpm)
rest(0.8, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.063, bpm)
keypress("8", x, bpm)
rest(0.063, bpm)
keypress("0", x, bpm)
rest(0.07, bpm)
keypress("e", x, bpm)
rest(1.403, bpm)
keypress("k", x, bpm)
rest(0.8, bpm)
keypress("G", x, bpm)
rest(0.4, bpm)
keypress("G", x, bpm)
rest(0.4, bpm)
keypress("k", x, bpm)
rest(1.2, bpm)
keypress("z", x, bpm)
rest(1.2, bpm)
keypress("l", x, bpm)
rest(0.8, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
rest(0.023, bpm)
keypress("%", x, bpm)
rest(0.033, bpm)
keypress("7", x, bpm)
rest(0.03, bpm)
keypress("0", x, bpm)
rest(1.513, bpm)
keypress("k", x, bpm)
rest(1.6, bpm)
keypress("k", x, bpm)
rest(1.2, bpm)
keypress("z", x, bpm)
rest(1.2, bpm)
keypress("l", x, bpm)
rest(0.8, bpm)
keypress("k", x, bpm)
rest(0.8, bpm)
keypress("f", x, bpm)
rest(0.8, bpm)
keypress("f", x, bpm)
rest(0.8, bpm)
keypress("k", x, bpm)
rest(0.8, bpm)
keypress("f", x, bpm)
rest(0.4, bpm)
keypress("f", x, bpm)
rest(0.4, bpm)
keypress("f", x, bpm)
rest(0.4, bpm)
keypress("f", x, bpm)
rest(0.4, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.4, bpm)
keypress("k", x, bpm)
rest(0.4, bpm)
keypress("k", x, bpm)
rest(0.8, bpm)
keypress("k", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1.6, bpm)
keypress("k", x, bpm)
rest(1.6, bpm)
keypress("k", x, bpm)
rest(1.2, bpm)
keypress("z", x, bpm)
rest(1.2, bpm)
keypress("l", x, bpm)
rest(0.8, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1.6, bpm)
keypress("k", x, bpm)
rest(0.8, bpm)
keypress("G", x, bpm)
rest(0.4, bpm)
keypress("G", x, bpm)
rest(0.4, bpm)
keypress("k", x, bpm)
rest(1.2, bpm)
keypress("z", x, bpm)
rest(1.2, bpm)
keypress("l", x, bpm)
rest(0.8, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(1.6, bpm)
keypress("k", x, bpm)
rest(1.6, bpm)
keypress("k", x, bpm)
rest(1.2, bpm)
keypress("z", x, bpm)
rest(1.2, bpm)
keypress("l", x, bpm)
rest(0.8, bpm)
keypress("k", x, bpm)
rest(0.779, bpm)
keypress("f", x, bpm)
rest(0.78, bpm)
keypress("f", x, bpm)
rest(0.783, bpm)
keypress("k", x, bpm)
rest(0.791, bpm)
keypress("f", x, bpm)
rest(0.402, bpm)
keypress("f", x, bpm)
rest(0.406, bpm)
keypress("f", x, bpm)
rest(0.411, bpm)
keypress("f", x, bpm)
rest(0.417, bpm)
keypress("k", x, bpm)
rest(0.424, bpm)
keypress("k", x, bpm)
rest(0.432, bpm)
keypress("k", x, bpm)
rest(0.882, bpm)
keypress("k", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)

finishedSong()