keypress("6", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(2, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(2, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(2, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(2, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(2, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(2, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(2, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(2, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(2, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(2, bpm)
keypress("f", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(2, bpm)
keypress("g", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(2, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(2, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(2, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(2, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(2, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(2, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(2, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(2, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(2, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(2, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(2, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(2, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(2, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(2, bpm)
keypress("f", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(2, bpm)
keypress("g", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(2, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(2, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(2, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(2, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(2, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
keypress("3", x, bpm)
keypress("6", x, bpm)

finishedSong()