keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
rest(2.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
rest(2.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
rest(1.5, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(1.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
rest(1.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(1.25, bpm)
keypress("i", x, bpm)
rest(0.092, bpm)
keypress("O", x, bpm)
rest(0.408, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
rest(1.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(1.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(1.25, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
rest(4.5, bpm)
keypress("Y", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("D", x, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("D", x, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("D", x, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("D", x, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
rest(2.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
rest(2.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
rest(2, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
rest(1.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
rest(1.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(1.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
rest(0.167, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
rest(4.5, bpm)
keypress("Y", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("D", x, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("D", x, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("D", x, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.75, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("D", x, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.75, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.75, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("l", x, bpm)
rest(0.167, bpm)
keypress("J", x, bpm)
rest(0.167, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(2.5, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.75, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.75, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("D", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.75, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("D", x, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.75, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("s", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.75, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("D", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("D", x, bpm)
keypress("g", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
rest(2.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)
rest(2.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("4", x, bpm)
rest(1.5, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
rest(2.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("!", x, bpm)

finishedSong()