keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(3, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("a", x, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(3, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(2, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(4, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(4, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
rest(0.125, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
rest(0.125, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
rest(0.125, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.136, bpm)
keypress("h", x, bpm)
rest(0.136, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.136, bpm)
keypress("h", x, bpm)
rest(0.136, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.155, bpm)
keypress("h", x, bpm)
rest(0.155, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.155, bpm)
keypress("h", x, bpm)
rest(0.155, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
rest(0.155, bpm)
keypress("k", x, bpm)
rest(0.155, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
rest(0.155, bpm)
keypress("k", x, bpm)
rest(0.155, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
rest(0.181, bpm)
keypress("k", x, bpm)
rest(0.181, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
rest(0.181, bpm)
keypress("k", x, bpm)
rest(0.181, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(7, bpm)
keypress("o", x, bpm)
rest(1.5, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("p", x, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(3, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("a", x, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(3, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(2, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(4, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(4, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
rest(0.125, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
rest(0.125, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
rest(0.125, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.136, bpm)
keypress("h", x, bpm)
rest(0.136, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.136, bpm)
keypress("h", x, bpm)
rest(0.136, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.136, bpm)
keypress("h", x, bpm)
rest(0.136, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
rest(0.136, bpm)
keypress("h", x, bpm)
rest(0.136, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
rest(0.155, bpm)
keypress("k", x, bpm)
rest(0.155, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
rest(0.155, bpm)
keypress("k", x, bpm)
rest(0.155, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
rest(0.181, bpm)
keypress("k", x, bpm)
rest(0.181, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
rest(0.181, bpm)
keypress("k", x, bpm)
rest(0.181, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(4, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(2, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(2, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(4, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(2, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(2, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(2, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(2, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("C", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)

finishedSong()