keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(3, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(3, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
rest(2, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("J", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("Z", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("Z", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("J", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("Z", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("Z", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.517, bpm)
keypress("D", x, bpm)
rest(0.533, bpm)
keypress("l", x, bpm)
keypress("^", x, bpm)
rest(0.533, bpm)
keypress("h", x, bpm)
rest(0.533, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.533, bpm)
keypress("l", x, bpm)
rest(0.571, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.571, bpm)
keypress("D", x, bpm)
rest(0.571, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(1.165, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1.231, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1.231, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(1.333, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1.333, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1.333, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(4, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(4, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)

finishedSong()