keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("r", x, bpm)
keypress("%", x, bpm)
keypress("2", x, bpm)
keypress("%", x, bpm)
rest(4, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(4, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
rest(4, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(2, bpm)
keypress("@", x, bpm)
rest(2, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
rest(4, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
keypress("1", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(8.667, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.26, bpm)
keypress("7", x, bpm)
rest(0.26, bpm)
keypress("(", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("0", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
rest(0.26, bpm)
keypress("J", x, bpm)
keypress("%", x, bpm)
rest(0.26, bpm)
keypress("k", x, bpm)
keypress("(", x, bpm)
rest(0.26, bpm)
keypress("0", x, bpm)
rest(0.26, bpm)
keypress("Z", x, bpm)
keypress("(", x, bpm)
rest(0.26, bpm)
keypress("%", x, bpm)
rest(0.26, bpm)
keypress("(", x, bpm)
rest(0.26, bpm)
keypress("0", x, bpm)
rest(0.26, bpm)
keypress("(", x, bpm)
rest(0.26, bpm)
keypress("%", x, bpm)
rest(0.26, bpm)
keypress("(", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("Z", x, bpm)
keypress("0", x, bpm)
rest(0.26, bpm)
keypress("L", x, bpm)
keypress("%", x, bpm)
rest(0.26, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.26, bpm)
keypress("f", x, bpm)
keypress("W", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
rest(0.26, bpm)
keypress("O", x, bpm)
keypress("E", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("r", x, bpm)
rest(0.26, bpm)
keypress("f", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("u", x, bpm)
rest(0.26, bpm)
keypress("O", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
rest(0.26, bpm)
keypress("f", x, bpm)
keypress("%", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("^", x, bpm)
rest(0.26, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
rest(0.26, bpm)
keypress("f", x, bpm)
rest(0.26, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.26, bpm)
keypress("$", x, bpm)
rest(0.26, bpm)
keypress("Q", x, bpm)
rest(0.26, bpm)
keypress("J", x, bpm)
keypress("W", x, bpm)
rest(0.26, bpm)
keypress("J", x, bpm)
keypress("Q", x, bpm)
rest(0.26, bpm)
keypress("k", x, bpm)
keypress("^", x, bpm)
rest(0.26, bpm)
keypress("J", x, bpm)
keypress("Q", x, bpm)
rest(0.26, bpm)
keypress("W", x, bpm)
rest(0.26, bpm)
keypress("k", x, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("Q", x, bpm)
rest(0.26, bpm)
keypress("^", x, bpm)
rest(0.26, bpm)
keypress("Q", x, bpm)
rest(0.26, bpm)
keypress("W", x, bpm)
rest(0.26, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
rest(0.26, bpm)
keypress("^", x, bpm)
rest(0.26, bpm)
keypress("Q", x, bpm)
rest(0.26, bpm)
keypress("W", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("x", x, bpm)
keypress("$", x, bpm)
rest(0.26, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("r", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
rest(0.26, bpm)
keypress("a", x, bpm)
keypress("u", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
keypress("$", x, bpm)
keypress("Y", x, bpm)
rest(0.028, bpm)
keypress("(", x, bpm)
rest(0.232, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.26, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.26, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.26, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.13, bpm)
keypress("D", x, bpm)
rest(0.13, bpm)
keypress("J", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.13, bpm)
keypress("k", x, bpm)
rest(0.13, bpm)
keypress("J", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.26, bpm)
keypress("(", x, bpm)
rest(0.26, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("r", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.26, bpm)
keypress("J", x, bpm)
keypress("%", x, bpm)
rest(0.26, bpm)
keypress("k", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.26, bpm)
keypress("V", x, bpm)
keypress("r", x, bpm)
rest(0.26, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
keypress("r", x, bpm)
rest(0.26, bpm)
keypress("k", x, bpm)
keypress("^", x, bpm)
keypress("W", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("W", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("O", x, bpm)
rest(0.26, bpm)
keypress("k", x, bpm)
keypress("I", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("*", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("Q", x, bpm)
keypress("Y", x, bpm)
rest(0.26, bpm)
keypress("k", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(0.26, bpm)
keypress("k", x, bpm)
keypress("W", x, bpm)
rest(0.26, bpm)
keypress("*", x, bpm)
rest(0.26, bpm)
keypress("C", x, bpm)
keypress("$", x, bpm)
rest(0.26, bpm)
keypress("!", x, bpm)
rest(0.26, bpm)
keypress("Q", x, bpm)
rest(0.26, bpm)
keypress("V", x, bpm)
keypress("E", x, bpm)
rest(0.26, bpm)
keypress("C", x, bpm)
keypress("T", x, bpm)
rest(0.26, bpm)
keypress("r", x, bpm)
rest(0.26, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
rest(0.26, bpm)
keypress("E", x, bpm)
rest(0.26, bpm)
keypress("T", x, bpm)
rest(0.26, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("7", x, bpm)
rest(0.26, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.26, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.26, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("E", x, bpm)
rest(0.26, bpm)
keypress("7", x, bpm)
keypress("E", x, bpm)
rest(0.26, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.26, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(0.26, bpm)
keypress("a", x, bpm)
keypress("Y", x, bpm)
rest(0.26, bpm)
keypress("7", x, bpm)
rest(0.26, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("T", x, bpm)
rest(0.26, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.26, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.26, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(0.26, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("E", x, bpm)
rest(0.26, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.26, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.26, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
rest(0.26, bpm)
keypress("a", x, bpm)
rest(0.26, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
keypress("E", x, bpm)
rest(0.26, bpm)
keypress("J", x, bpm)
keypress("7", x, bpm)
keypress("E", x, bpm)
rest(0.26, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("r", x, bpm)
rest(0.26, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.26, bpm)
keypress("7", x, bpm)
rest(0.26, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(0.26, bpm)
keypress("(", x, bpm)
rest(0.26, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.26, bpm)
keypress("@", x, bpm)
rest(0.26, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.26, bpm)
keypress("*", x, bpm)
rest(0.26, bpm)
keypress("(", x, bpm)
rest(2.34, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.045, bpm)
keypress("7", x, bpm)
rest(0.045, bpm)
keypress("8", x, bpm)
keypress("1", x, bpm)
rest(0.045, bpm)
keypress("9", x, bpm)
keypress("2", x, bpm)
rest(0.045, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
rest(0.045, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.045, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.045, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.045, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.045, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.045, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.045, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.045, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.045, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.045, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.045, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.045, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.045, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.045, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
rest(0.045, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
rest(0.045, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
rest(0.045, bpm)
keypress("j", x, bpm)
keypress("p", x, bpm)
rest(0.045, bpm)
keypress("k", x, bpm)
keypress("a", x, bpm)
rest(0.045, bpm)
keypress("l", x, bpm)
keypress("s", x, bpm)
rest(0.045, bpm)
keypress("z", x, bpm)
keypress("d", x, bpm)
rest(0.045, bpm)
keypress("x", x, bpm)
keypress("f", x, bpm)
rest(0.045, bpm)
keypress("c", x, bpm)
keypress("g", x, bpm)
rest(0.045, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(0.173, bpm)
keypress("%", x, bpm)
rest(0.173, bpm)
keypress("W", x, bpm)
rest(0.173, bpm)
keypress("H", x, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
keypress("(", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.13, bpm)
keypress("H", x, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.13, bpm)
keypress("%", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.26, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
keypress("n", x, bpm)
keypress("Q", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.26, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("B", x, bpm)
keypress("$", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
rest(0.173, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.173, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.173, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("E", x, bpm)
keypress("I", x, bpm)
rest(0.26, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(0.13, bpm)
keypress("J", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.13, bpm)
keypress("^", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("V", x, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.26, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("B", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.26, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("L", x, bpm)
keypress("E", x, bpm)
keypress("I", x, bpm)
rest(0.26, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
keypress("n", x, bpm)
keypress("%", x, bpm)
rest(0.173, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.173, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.173, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("n", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.26, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.13, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("n", x, bpm)
keypress("r", x, bpm)
keypress("O", x, bpm)
rest(0.13, bpm)
keypress("(", x, bpm)
rest(0.26, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
keypress("B", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.26, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("n", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.26, bpm)
keypress("L", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
rest(0.26, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
keypress("n", x, bpm)
keypress("Z", x, bpm)
keypress("7", x, bpm)
rest(0.173, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.173, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.173, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.173, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.173, bpm)
keypress("^", x, bpm)
rest(0.173, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
keypress("n", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.26, bpm)
keypress("!", x, bpm)
rest(0.13, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("B", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.26, bpm)
keypress("$", x, bpm)
rest(0.13, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("C", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("V", x, bpm)
keypress("3", x, bpm)
rest(0.173, bpm)
keypress("7", x, bpm)
rest(0.173, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.173, bpm)
keypress("(", x, bpm)
keypress("r", x, bpm)
rest(0.173, bpm)
keypress("0", x, bpm)
rest(0.087, bpm)
keypress("H", x, bpm)
rest(0.087, bpm)
keypress("7", x, bpm)
rest(0.173, bpm)
keypress("H", x, bpm)
keypress("Q", x, bpm)
rest(0.173, bpm)
keypress("r", x, bpm)
rest(0.087, bpm)
keypress("G", x, bpm)
rest(0.087, bpm)
keypress("%", x, bpm)
rest(0.173, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
rest(0.13, bpm)
keypress("%", x, bpm)
rest(0.13, bpm)
keypress("Z", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
keypress("W", x, bpm)
rest(0.173, bpm)
keypress("k", x, bpm)
rest(0.087, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
rest(0.087, bpm)
keypress("G", x, bpm)
rest(0.173, bpm)
keypress("P", x, bpm)
keypress("D", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
rest(0.13, bpm)
keypress("f", x, bpm)
rest(0.13, bpm)
keypress("Z", x, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(0.26, bpm)
keypress("L", x, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.26, bpm)
keypress("Z", x, bpm)
keypress("T", x, bpm)
rest(0.26, bpm)
keypress("C", x, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
rest(0.26, bpm)
keypress("L", x, bpm)
keypress("*", x, bpm)
rest(0.26, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.173, bpm)
keypress("r", x, bpm)
rest(0.087, bpm)
keypress("Z", x, bpm)
rest(0.087, bpm)
keypress("7", x, bpm)
keypress("W", x, bpm)
rest(0.173, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
rest(0.13, bpm)
keypress("0", x, bpm)
rest(0.13, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("(", x, bpm)
keypress("T", x, bpm)
rest(0.173, bpm)
keypress("J", x, bpm)
rest(0.087, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.087, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
rest(0.173, bpm)
keypress("G", x, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
rest(0.173, bpm)
keypress("J", x, bpm)
rest(0.087, bpm)
keypress("(", x, bpm)
keypress("T", x, bpm)
rest(0.087, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
rest(0.173, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.173, bpm)
keypress("J", x, bpm)
rest(0.087, bpm)
keypress("Q", x, bpm)
keypress("Y", x, bpm)
rest(0.087, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
rest(0.173, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.13, bpm)
keypress("J", x, bpm)
rest(0.13, bpm)
keypress("Z", x, bpm)
keypress("(", x, bpm)
keypress("r", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("L", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.173, bpm)
keypress("Q", x, bpm)
rest(0.087, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
rest(0.087, bpm)
keypress("(", x, bpm)
keypress("r", x, bpm)
rest(0.173, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
keypress("7", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("T", x, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("r", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("r", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.13, bpm)
keypress("Z", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.13, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("r", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("L", x, bpm)
keypress("r", x, bpm)
keypress("Q", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("r", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.26, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("P", x, bpm)
rest(0.26, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.26, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("T", x, bpm)
keypress("E", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.26, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("T", x, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
rest(0.13, bpm)
keypress("L", x, bpm)
keypress("E", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.13, bpm)
keypress("J", x, bpm)
keypress("T", x, bpm)
rest(0.26, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
rest(0.26, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("P", x, bpm)
rest(0.26, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("B", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
rest(0.26, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
keypress("n", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.26, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.26, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
keypress("Y", x, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
rest(0.26, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
keypress("Y", x, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
rest(0.13, bpm)
keypress("V", x, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
rest(0.13, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("Y", x, bpm)
rest(0.26, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
rest(0.26, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("a", x, bpm)
rest(0.26, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("B", x, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.26, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
keypress("n", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.26, bpm)
keypress("7", x, bpm)
rest(0.26, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("B", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
rest(0.26, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.26, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.13, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("T", x, bpm)
keypress("P", x, bpm)
rest(0.26, bpm)
keypress("Q", x, bpm)
rest(0.13, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
keypress("n", x, bpm)
keypress("Z", x, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.26, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
keypress("n", x, bpm)
keypress("Z", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(0.173, bpm)
keypress("7", x, bpm)
rest(0.087, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
rest(0.087, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.173, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
keypress("W", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("^", x, bpm)
rest(0.13, bpm)
keypress("E", x, bpm)
rest(0.13, bpm)
keypress("$", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
rest(0.26, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("*", x, bpm)
rest(0.26, bpm)
keypress("Z", x, bpm)
keypress("n", x, bpm)
keypress("Z", x, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
rest(0.26, bpm)
keypress("^", x, bpm)
keypress("*", x, bpm)
keypress("E", x, bpm)
rest(0.13, bpm)
keypress("L", x, bpm)
rest(0.13, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.26, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
keypress("W", x, bpm)
rest(0.26, bpm)
keypress("k", x, bpm)
keypress("V", x, bpm)
keypress("n", x, bpm)
keypress("%", x, bpm)
rest(0.26, bpm)
keypress("J", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("%", x, bpm)
rest(0.26, bpm)
keypress("J", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.26, bpm)
keypress("%", x, bpm)
rest(0.26, bpm)
keypress("(", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("r", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(0.26, bpm)
keypress("W", x, bpm)
rest(0.26, bpm)
keypress("(", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("W", x, bpm)
rest(0.26, bpm)
keypress("%", x, bpm)
rest(0.26, bpm)
keypress("%", x, bpm)
rest(0.173, bpm)
keypress("O", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.173, bpm)
keypress("Y", x, bpm)
rest(0.173, bpm)
keypress("O", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.173, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("Y", x, bpm)
rest(0.173, bpm)
keypress("O", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.173, bpm)
keypress("Y", x, bpm)
rest(0.173, bpm)
keypress("O", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.173, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.173, bpm)
keypress("O", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
keypress("S", x, bpm)
rest(0.173, bpm)
keypress("T", x, bpm)
rest(0.173, bpm)
keypress("O", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
keypress("S", x, bpm)
rest(0.173, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("T", x, bpm)
rest(0.173, bpm)
keypress("O", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
keypress("S", x, bpm)
rest(0.173, bpm)
keypress("T", x, bpm)
rest(0.173, bpm)
keypress("O", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
keypress("S", x, bpm)
rest(0.173, bpm)
keypress("u", x, bpm)
keypress("%", x, bpm)
rest(0.173, bpm)
keypress("O", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.173, bpm)
keypress("u", x, bpm)
rest(0.173, bpm)
keypress("O", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.173, bpm)
keypress("u", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.173, bpm)
keypress("O", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.173, bpm)
keypress("u", x, bpm)
rest(0.173, bpm)
keypress("O", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.173, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("Y", x, bpm)
rest(0.173, bpm)
keypress("O", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.173, bpm)
keypress("Y", x, bpm)
rest(0.173, bpm)
keypress("O", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.173, bpm)
keypress("Y", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.173, bpm)
keypress("O", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.173, bpm)
keypress("Y", x, bpm)
rest(0.173, bpm)
keypress("O", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.173, bpm)
keypress("I", x, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.173, bpm)
keypress("P", x, bpm)
rest(0.173, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.173, bpm)
keypress("I", x, bpm)
rest(0.173, bpm)
keypress("P", x, bpm)
rest(0.173, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.173, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("I", x, bpm)
rest(0.173, bpm)
keypress("P", x, bpm)
rest(0.173, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.173, bpm)
keypress("I", x, bpm)
rest(0.173, bpm)
keypress("P", x, bpm)
rest(0.173, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.173, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.173, bpm)
keypress("I", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
keypress("S", x, bpm)
rest(0.173, bpm)
keypress("T", x, bpm)
rest(0.173, bpm)
keypress("I", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
keypress("S", x, bpm)
rest(0.173, bpm)
keypress("L", x, bpm)
keypress("x", x, bpm)
keypress("T", x, bpm)
rest(0.173, bpm)
keypress("I", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
keypress("S", x, bpm)
rest(0.173, bpm)
keypress("T", x, bpm)
rest(0.173, bpm)
keypress("I", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
keypress("S", x, bpm)
rest(0.173, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.173, bpm)
keypress("I", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.173, bpm)
keypress("u", x, bpm)
rest(0.173, bpm)
keypress("I", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.173, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("u", x, bpm)
rest(0.173, bpm)
keypress("I", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.173, bpm)
keypress("u", x, bpm)
rest(0.173, bpm)
keypress("I", x, bpm)
rest(0.087, bpm)
keypress("x", x, bpm)
rest(0.087, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.173, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.173, bpm)
keypress("I", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.173, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
keypress("r", x, bpm)
rest(0.173, bpm)
keypress("I", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.173, bpm)
keypress("Y", x, bpm)
keypress("0", x, bpm)
keypress("T", x, bpm)
rest(0.173, bpm)
keypress("I", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.173, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
keypress("r", x, bpm)
rest(0.173, bpm)
keypress("I", x, bpm)
rest(0.087, bpm)
keypress("E", x, bpm)
rest(0.087, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.173, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.035, bpm)
keypress("a", x, bpm)
rest(0.037, bpm)
keypress("D", x, bpm)
rest(0.036, bpm)
keypress("H", x, bpm)
rest(0.673, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
keypress("3", x, bpm)
rest(0.13, bpm)
keypress("O", x, bpm)
rest(0.13, bpm)
keypress("H", x, bpm)
rest(0.13, bpm)
keypress("O", x, bpm)
rest(0.13, bpm)
keypress("J", x, bpm)
rest(0.13, bpm)
keypress("P", x, bpm)
rest(0.13, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(0.13, bpm)
keypress("a", x, bpm)
rest(0.13, bpm)
keypress("V", x, bpm)
rest(0.13, bpm)
keypress("H", x, bpm)
rest(0.13, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(0.78, bpm)
keypress("k", x, bpm)
keypress("%", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.07, bpm)
keypress("n", x, bpm)
rest(0.19, bpm)
keypress("W", x, bpm)
rest(0.26, bpm)
keypress("E", x, bpm)
rest(0.26, bpm)
keypress("J", x, bpm)
keypress("W", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.071, bpm)
keypress("B", x, bpm)
rest(0.188, bpm)
keypress("I", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
rest(0.07, bpm)
keypress("C", x, bpm)
rest(0.45, bpm)
keypress("Y", x, bpm)
rest(0.26, bpm)
keypress("T", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("Q", x, bpm)
rest(0.07, bpm)
keypress("V", x, bpm)
rest(0.19, bpm)
keypress("r", x, bpm)
rest(0.52, bpm)
keypress("I", x, bpm)
rest(0.26, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
rest(0.07, bpm)
keypress("B", x, bpm)
rest(0.45, bpm)
keypress("H", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
rest(0.26, bpm)
keypress("k", x, bpm)
keypress("Q", x, bpm)
rest(0.07, bpm)
keypress("n", x, bpm)
rest(0.19, bpm)
keypress("S", x, bpm)
rest(0.78, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
rest(0.071, bpm)
keypress("3", x, bpm)
rest(0.071, bpm)
keypress("7", x, bpm)
rest(0.073, bpm)
keypress("Q", x, bpm)
rest(0.304, bpm)
keypress("T", x, bpm)
rest(0.26, bpm)
keypress("E", x, bpm)
rest(0.26, bpm)
keypress("E", x, bpm)
rest(0.26, bpm)
keypress("r", x, bpm)
rest(0.26, bpm)
keypress("T", x, bpm)
rest(0.26, bpm)
keypress("Y", x, bpm)
rest(0.26, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
rest(0.26, bpm)
keypress("T", x, bpm)
rest(0.26, bpm)
keypress("$", x, bpm)
rest(0.26, bpm)
keypress("r", x, bpm)
rest(0.26, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.26, bpm)
keypress("E", x, bpm)
rest(0.26, bpm)
keypress("^", x, bpm)
rest(0.52, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.071, bpm)
keypress("7", x, bpm)
rest(0.071, bpm)
keypress("Q", x, bpm)
rest(0.377, bpm)
keypress("I", x, bpm)
keypress("3", x, bpm)
rest(0.26, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(0.26, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("k", x, bpm)
keypress("r", x, bpm)
rest(0.26, bpm)
keypress("f", x, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("Z", x, bpm)
keypress("Y", x, bpm)
rest(0.26, bpm)
keypress("7", x, bpm)
rest(0.26, bpm)
keypress("f", x, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
rest(0.26, bpm)
keypress("Q", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("r", x, bpm)
rest(0.26, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.26, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
rest(0.78, bpm)
keypress("r", x, bpm)
rest(0.031, bpm)
keypress("I", x, bpm)
rest(0.032, bpm)
keypress("O", x, bpm)
rest(0.033, bpm)
keypress("a", x, bpm)
rest(0.032, bpm)
keypress("D", x, bpm)
rest(0.033, bpm)
keypress("G", x, bpm)
rest(0.033, bpm)
keypress("H", x, bpm)
rest(0.032, bpm)
keypress("Z", x, bpm)
rest(0.955, bpm)
keypress("Z", x, bpm)
keypress("L", x, bpm)
rest(0.52, bpm)
keypress("Z", x, bpm)
rest(0.26, bpm)
keypress("Z", x, bpm)
rest(0.26, bpm)
keypress("V", x, bpm)
rest(0.52, bpm)
keypress("L", x, bpm)
rest(0.52, bpm)
keypress("Z", x, bpm)
rest(0.52, bpm)
keypress("C", x, bpm)
rest(0.52, bpm)
keypress("Z", x, bpm)
keypress("P", x, bpm)
rest(0.063, bpm)
keypress("D", x, bpm)
rest(0.066, bpm)
keypress("G", x, bpm)
rest(0.065, bpm)
keypress("J", x, bpm)
rest(0.065, bpm)
keypress("Z", x, bpm)
rest(0.781, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("E", x, bpm)
keypress("S", x, bpm)
rest(0.071, bpm)
keypress("I", x, bpm)
rest(0.448, bpm)
keypress("D", x, bpm)
rest(0.26, bpm)
keypress("S", x, bpm)
rest(0.26, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
rest(0.52, bpm)
keypress("a", x, bpm)
rest(0.26, bpm)
keypress("T", x, bpm)
rest(0.26, bpm)
keypress("L", x, bpm)
keypress("S", x, bpm)
rest(0.52, bpm)
keypress("Q", x, bpm)
keypress("S", x, bpm)
rest(0.52, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("S", x, bpm)
keypress("W", x, bpm)
rest(0.07, bpm)
keypress("Y", x, bpm)
rest(0.073, bpm)
keypress("O", x, bpm)
rest(0.073, bpm)
keypress("D", x, bpm)
rest(0.824, bpm)
keypress("n", x, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.52, bpm)
keypress("n", x, bpm)
rest(0.26, bpm)
keypress("L", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
rest(0.52, bpm)
keypress("C", x, bpm)
rest(0.52, bpm)
keypress("Z", x, bpm)
keypress("$", x, bpm)
rest(0.52, bpm)
keypress("L", x, bpm)
rest(0.52, bpm)
keypress("Z", x, bpm)
keypress("O", x, bpm)
rest(0.07, bpm)
keypress("a", x, bpm)
rest(0.073, bpm)
keypress("D", x, bpm)
rest(0.073, bpm)
keypress("G", x, bpm)
rest(0.071, bpm)
keypress("L", x, bpm)
rest(0.753, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("a", x, bpm)
rest(0.52, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
rest(0.26, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.26, bpm)
keypress("J", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("%", x, bpm)
rest(0.173, bpm)
keypress("x", x, bpm)
rest(0.173, bpm)
keypress("Z", x, bpm)
rest(0.173, bpm)
keypress("L", x, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.173, bpm)
keypress("k", x, bpm)
rest(0.173, bpm)
keypress("J", x, bpm)
rest(0.173, bpm)
keypress("G", x, bpm)
keypress("Z", x, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.173, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.173, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.173, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
rest(0.173, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
rest(0.173, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("3", x, bpm)
rest(0.173, bpm)
keypress("3", x, bpm)
rest(0.173, bpm)
keypress("7", x, bpm)
rest(0.173, bpm)
keypress("0", x, bpm)
rest(0.173, bpm)
keypress("7", x, bpm)
rest(0.173, bpm)
keypress("W", x, bpm)
rest(0.173, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.173, bpm)
keypress("W", x, bpm)
rest(0.173, bpm)
keypress("r", x, bpm)
rest(0.173, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.173, bpm)
keypress("O", x, bpm)
rest(0.087, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
rest(0.087, bpm)
keypress("u", x, bpm)
rest(0.173, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.173, bpm)
keypress("W", x, bpm)
rest(0.173, bpm)
keypress("r", x, bpm)
rest(0.173, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.173, bpm)
keypress("O", x, bpm)
rest(0.173, bpm)
keypress("u", x, bpm)
rest(0.173, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.173, bpm)
keypress("W", x, bpm)
rest(0.173, bpm)
keypress("r", x, bpm)
rest(0.173, bpm)
keypress("0", x, bpm)
rest(0.173, bpm)
keypress("7", x, bpm)
rest(0.087, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.087, bpm)
keypress("3", x, bpm)
rest(0.173, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("$", x, bpm)
rest(0.173, bpm)
keypress("$", x, bpm)
rest(0.173, bpm)
keypress("$", x, bpm)
rest(0.173, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("^", x, bpm)
rest(0.173, bpm)
keypress("Q", x, bpm)
rest(0.173, bpm)
keypress("*", x, bpm)
rest(0.173, bpm)
keypress("E", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.173, bpm)
keypress("P", x, bpm)
rest(0.087, bpm)
keypress("T", x, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(0.087, bpm)
keypress("S", x, bpm)
rest(0.173, bpm)
keypress("G", x, bpm)
keypress("T", x, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(0.173, bpm)
keypress("S", x, bpm)
rest(0.087, bpm)
keypress("T", x, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(0.087, bpm)
keypress("J", x, bpm)
rest(0.173, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
keypress("r", x, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(0.173, bpm)
keypress("G", x, bpm)
rest(0.087, bpm)
keypress("$", x, bpm)
rest(0.087, bpm)
keypress("J", x, bpm)
rest(0.173, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(0.173, bpm)
keypress("B", x, bpm)
rest(0.087, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.087, bpm)
keypress("C", x, bpm)
rest(0.173, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(0.173, bpm)
keypress("G", x, bpm)
rest(0.087, bpm)
keypress("Q", x, bpm)
rest(0.087, bpm)
keypress("J", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.173, bpm)
keypress("S", x, bpm)
rest(0.087, bpm)
keypress("Q", x, bpm)
rest(0.087, bpm)
keypress("I", x, bpm)
rest(0.173, bpm)
keypress("E", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.173, bpm)
keypress("%", x, bpm)
rest(0.173, bpm)
keypress("(", x, bpm)
rest(0.173, bpm)
keypress("W", x, bpm)
rest(0.173, bpm)
keypress("r", x, bpm)
rest(0.173, bpm)
keypress("W", x, bpm)
rest(0.173, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
rest(0.173, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.173, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
rest(0.087, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
rest(0.087, bpm)
keypress("E", x, bpm)
keypress("I", x, bpm)
rest(0.173, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
rest(0.173, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.173, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("r", x, bpm)
keypress("P", x, bpm)
rest(0.173, bpm)
keypress("Y", x, bpm)
keypress("a", x, bpm)
rest(0.173, bpm)
keypress("E", x, bpm)
keypress("I", x, bpm)
rest(0.173, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
rest(0.173, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
rest(0.173, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(0.173, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.173, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.173, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.173, bpm)
keypress("k", x, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
rest(0.173, bpm)
keypress("Z", x, bpm)
keypress("n", x, bpm)
rest(0.087, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.087, bpm)
keypress("J", x, bpm)
rest(0.173, bpm)
keypress("L", x, bpm)
keypress("B", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.173, bpm)
keypress("H", x, bpm)
rest(0.087, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.087, bpm)
keypress("k", x, bpm)
keypress("V", x, bpm)
rest(0.173, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(0.173, bpm)
keypress("J", x, bpm)
keypress("C", x, bpm)
rest(0.087, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(0.087, bpm)
keypress("G", x, bpm)
rest(0.173, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.173, bpm)
keypress("G", x, bpm)
rest(0.087, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.087, bpm)
keypress("k", x, bpm)
keypress("L", x, bpm)
rest(0.173, bpm)
keypress("a", x, bpm)
keypress("%", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.173, bpm)
keypress("D", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.173, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.173, bpm)
keypress("S", x, bpm)
keypress("J", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.173, bpm)
keypress("I", x, bpm)
rest(0.087, bpm)
keypress("$", x, bpm)
rest(0.087, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
rest(0.173, bpm)
keypress("I", x, bpm)
keypress("(", x, bpm)
keypress("Y", x, bpm)
rest(0.173, bpm)
keypress("P", x, bpm)
keypress("G", x, bpm)
rest(0.087, bpm)
keypress("$", x, bpm)
rest(0.087, bpm)
keypress("Y", x, bpm)
rest(0.173, bpm)
keypress("I", x, bpm)
keypress("D", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(0.173, bpm)
keypress("T", x, bpm)
rest(0.087, bpm)
keypress("$", x, bpm)
rest(0.087, bpm)
keypress("u", x, bpm)
keypress("S", x, bpm)
rest(0.173, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(0.78, bpm)
keypress("H", x, bpm)
keypress("Z", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("Z", x, bpm)
rest(0.52, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("Z", x, bpm)
rest(0.52, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("Z", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("Z", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
keypress("%", x, bpm)
rest(0.78, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
rest(0.52, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("k", x, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("Z", x, bpm)
rest(0.52, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
rest(0.26, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("Z", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.78, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
rest(0.26, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
keypress("%", x, bpm)
rest(0.26, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
rest(0.26, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("Z", x, bpm)
rest(0.26, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("D", x, bpm)
rest(0.26, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("Z", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("Z", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
rest(0.52, bpm)
keypress("%", x, bpm)
rest(0.028, bpm)
keypress("@", x, bpm)
rest(0.028, bpm)
keypress("%", x, bpm)
rest(0.204, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("V", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
keypress("%", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("%", x, bpm)
rest(0.52, bpm)
keypress("J", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.26, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
keypress("n", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
rest(0.26, bpm)
keypress("J", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("^", x, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
rest(0.52, bpm)
keypress("C", x, bpm)
keypress("n", x, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.52, bpm)
keypress("C", x, bpm)
keypress("n", x, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.52, bpm)
keypress("V", x, bpm)
keypress("n", x, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
keypress("%", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(3.76, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("$", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(0.173, bpm)
keypress("7", x, bpm)
rest(0.173, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.173, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("Z", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.173, bpm)
keypress("3", x, bpm)
rest(0.087, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("Z", x, bpm)
rest(0.087, bpm)
keypress("7", x, bpm)
rest(0.043, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("Z", x, bpm)
rest(0.13, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.173, bpm)
keypress("3", x, bpm)
rest(0.087, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("L", x, bpm)
rest(0.087, bpm)
keypress("7", x, bpm)
rest(0.173, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("Z", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.173, bpm)
keypress("3", x, bpm)
rest(0.087, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
keypress("C", x, bpm)
rest(0.087, bpm)
keypress("7", x, bpm)
rest(0.173, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("$", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
rest(0.173, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.173, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.173, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("C", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.173, bpm)
keypress("$", x, bpm)
rest(0.087, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("C", x, bpm)
rest(0.087, bpm)
keypress("*", x, bpm)
rest(0.043, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
rest(0.13, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.173, bpm)
keypress("$", x, bpm)
rest(0.087, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("J", x, bpm)
rest(0.087, bpm)
keypress("*", x, bpm)
rest(0.173, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.173, bpm)
keypress("$", x, bpm)
rest(0.087, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
rest(0.087, bpm)
keypress("*", x, bpm)
rest(0.173, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
keypress("n", x, bpm)
keypress("%", x, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.173, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.173, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.173, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
keypress("V", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.173, bpm)
keypress("%", x, bpm)
rest(0.087, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
keypress("V", x, bpm)
rest(0.087, bpm)
keypress("(", x, bpm)
rest(0.043, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
keypress("V", x, bpm)
rest(0.13, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.173, bpm)
keypress("%", x, bpm)
rest(0.087, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("Z", x, bpm)
rest(0.087, bpm)
keypress("(", x, bpm)
rest(0.173, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
keypress("V", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
rest(0.173, bpm)
keypress("W", x, bpm)
rest(0.087, bpm)
keypress("L", x, bpm)
keypress("B", x, bpm)
rest(0.087, bpm)
keypress("(", x, bpm)
rest(0.173, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
keypress("n", x, bpm)
keypress("Z", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
rest(0.173, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.173, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.173, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("L", x, bpm)
keypress("n", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.173, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.087, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("L", x, bpm)
keypress("n", x, bpm)
rest(0.087, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.173, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
keypress("C", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.13, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
keypress("C", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.13, bpm)
keypress("*", x, bpm)
rest(0.13, bpm)
keypress("J", x, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("$", x, bpm)
rest(0.05, bpm)
keypress("E", x, bpm)
rest(0.21, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
rest(0.13, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("%", x, bpm)
rest(0.036, bpm)
keypress("(", x, bpm)
rest(0.036, bpm)
keypress("r", x, bpm)
rest(0.188, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(0.173, bpm)
keypress("7", x, bpm)
rest(0.173, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.173, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.173, bpm)
keypress("r", x, bpm)
rest(0.087, bpm)
keypress("H", x, bpm)
rest(0.087, bpm)
keypress("0", x, bpm)
rest(0.173, bpm)
keypress("H", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.173, bpm)
keypress("r", x, bpm)
rest(0.087, bpm)
keypress("G", x, bpm)
rest(0.087, bpm)
keypress("0", x, bpm)
rest(0.173, bpm)
keypress("H", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.173, bpm)
keypress("r", x, bpm)
rest(0.087, bpm)
keypress("Z", x, bpm)
keypress("H", x, bpm)
rest(0.087, bpm)
keypress("0", x, bpm)
rest(0.173, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.173, bpm)
keypress("Q", x, bpm)
rest(0.087, bpm)
keypress("G", x, bpm)
rest(0.087, bpm)
keypress("$", x, bpm)
rest(0.173, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.173, bpm)
keypress("E", x, bpm)
rest(0.087, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
rest(0.087, bpm)
keypress("Q", x, bpm)
rest(0.173, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.173, bpm)
keypress("E", x, bpm)
rest(0.087, bpm)
keypress("Z", x, bpm)
rest(0.087, bpm)
keypress("Q", x, bpm)
rest(0.173, bpm)
keypress("C", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.173, bpm)
keypress("E", x, bpm)
rest(0.087, bpm)
keypress("L", x, bpm)
rest(0.087, bpm)
keypress("Q", x, bpm)
rest(0.173, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.173, bpm)
keypress("W", x, bpm)
rest(0.087, bpm)
keypress("Z", x, bpm)
rest(0.087, bpm)
keypress("(", x, bpm)
rest(0.173, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.26, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.173, bpm)
keypress("W", x, bpm)
rest(0.087, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
rest(0.087, bpm)
keypress("(", x, bpm)
rest(0.173, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.173, bpm)
keypress("W", x, bpm)
rest(0.087, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.087, bpm)
keypress("(", x, bpm)
rest(0.173, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
rest(0.173, bpm)
keypress("7", x, bpm)
rest(0.087, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
rest(0.087, bpm)
keypress("Q", x, bpm)
rest(0.173, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.26, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("L", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.173, bpm)
keypress("r", x, bpm)
rest(0.087, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
rest(0.087, bpm)
keypress("Q", x, bpm)
rest(0.173, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
keypress("7", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.26, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.26, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.26, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.13, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.13, bpm)
keypress("D", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.13, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.13, bpm)
keypress("O", x, bpm)
rest(0.13, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
rest(0.13, bpm)
keypress("H", x, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.13, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
rest(0.13, bpm)
keypress("a", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.13, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
rest(0.13, bpm)
keypress("k", x, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.13, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
keypress("n", x, bpm)
rest(0.13, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.26, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.26, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.13, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.13, bpm)
keypress("G", x, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.13, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("T", x, bpm)
keypress("P", x, bpm)
rest(0.13, bpm)
keypress("S", x, bpm)
rest(0.13, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
rest(0.13, bpm)
keypress("J", x, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
rest(0.13, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
rest(0.13, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.13, bpm)
keypress("J", x, bpm)
keypress("L", x, bpm)
rest(0.13, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(0.13, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("L", x, bpm)
rest(0.13, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
keypress("n", x, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.26, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.26, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.13, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
rest(0.13, bpm)
keypress("k", x, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.13, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
keypress("n", x, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.13, bpm)
keypress("P", x, bpm)
rest(0.13, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
rest(0.13, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
rest(0.13, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
rest(0.13, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.13, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
rest(0.13, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
keypress("S", x, bpm)
rest(0.13, bpm)
keypress("C", x, bpm)
keypress("V", x, bpm)
keypress("L", x, bpm)
rest(0.13, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
keypress("n", x, bpm)
keypress("Z", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
rest(0.26, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
rest(0.26, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("n", x, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
rest(0.26, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.26, bpm)
keypress("k", x, bpm)
keypress("V", x, bpm)
keypress("n", x, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.13, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("B", x, bpm)
keypress("T", x, bpm)
keypress("P", x, bpm)
rest(0.26, bpm)
keypress("Q", x, bpm)
rest(0.13, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
keypress("n", x, bpm)
keypress("Z", x, bpm)
keypress("r", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.26, bpm)
keypress("Z", x, bpm)
keypress("V", x, bpm)
keypress("n", x, bpm)
keypress("Z", x, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(0.173, bpm)
keypress("7", x, bpm)
rest(0.173, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.173, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("W", x, bpm)
rest(0.26, bpm)
keypress("$", x, bpm)
keypress("^", x, bpm)
keypress("Q", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("^", x, bpm)
rest(0.13, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.13, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("$", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(0.26, bpm)
keypress("Z", x, bpm)
keypress("n", x, bpm)
keypress("Z", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
rest(0.26, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
rest(0.13, bpm)
keypress("L", x, bpm)
rest(0.13, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
rest(0.26, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(0.26, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
rest(0.26, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("P", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.26, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(0.26, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("7", x, bpm)
keypress("W", x, bpm)
rest(0.26, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("%", x, bpm)
rest(0.26, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("%", x, bpm)
rest(0.26, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("L", x, bpm)
keypress("(", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.26, bpm)
keypress("%", x, bpm)
rest(0.26, bpm)
keypress("(", x, bpm)
rest(0.26, bpm)
keypress("G", x, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
keypress("Q", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.26, bpm)
keypress("D", x, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("Y", x, bpm)
rest(0.26, bpm)
keypress("%", x, bpm)
keypress("W", x, bpm)
rest(0.26, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("D", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("@", x, bpm)
keypress("$", x, bpm)
rest(0.52, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("D", x, bpm)
keypress("H", x, bpm)
keypress("%", x, bpm)
rest(4.42, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
rest(0.162, bpm)
keypress("@", x, bpm)
rest(0.162, bpm)
keypress("%", x, bpm)
rest(0.162, bpm)
keypress("7", x, bpm)
rest(0.162, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
rest(0.081, bpm)
keypress("6", x, bpm)
rest(0.081, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.081, bpm)
keypress("7", x, bpm)
rest(0.081, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.162, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(0.162, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.102, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.162, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.162, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.102, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("@", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("3", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.162, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(0.162, bpm)
keypress("%", x, bpm)
rest(0.125, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.102, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("@", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.162, bpm)
keypress("%", x, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(0.162, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("^", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("1", x, bpm)
rest(0.065, bpm)
keypress("!", x, bpm)
rest(0.065, bpm)
keypress("@", x, bpm)
rest(0.065, bpm)
keypress("3", x, bpm)
rest(0.065, bpm)
keypress("4", x, bpm)
rest(0.065, bpm)
keypress("$", x, bpm)
rest(0.065, bpm)
keypress("5", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("^", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("8", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("^", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("5", x, bpm)
rest(0.065, bpm)
keypress("$", x, bpm)
rest(0.065, bpm)
keypress("4", x, bpm)
rest(0.065, bpm)
keypress("3", x, bpm)
rest(0.065, bpm)
keypress("@", x, bpm)
rest(0.065, bpm)
keypress("2", x, bpm)
rest(0.065, bpm)
keypress("!", x, bpm)
rest(0.065, bpm)
keypress("1", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.052, bpm)
keypress("^", x, bpm)
rest(0.052, bpm)
keypress("6", x, bpm)
rest(0.052, bpm)
keypress("%", x, bpm)
rest(0.052, bpm)
keypress("5", x, bpm)
rest(0.052, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("^", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("1", x, bpm)
rest(0.065, bpm)
keypress("!", x, bpm)
rest(0.065, bpm)
keypress("@", x, bpm)
rest(0.065, bpm)
keypress("3", x, bpm)
rest(0.065, bpm)
keypress("4", x, bpm)
rest(0.065, bpm)
keypress("$", x, bpm)
rest(0.065, bpm)
keypress("5", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("^", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("8", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("^", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("5", x, bpm)
rest(0.065, bpm)
keypress("$", x, bpm)
rest(0.065, bpm)
keypress("4", x, bpm)
rest(0.065, bpm)
keypress("3", x, bpm)
rest(0.065, bpm)
keypress("@", x, bpm)
rest(0.065, bpm)
keypress("2", x, bpm)
rest(0.065, bpm)
keypress("!", x, bpm)
rest(0.065, bpm)
keypress("1", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.052, bpm)
keypress("^", x, bpm)
rest(0.052, bpm)
keypress("6", x, bpm)
rest(0.052, bpm)
keypress("%", x, bpm)
rest(0.052, bpm)
keypress("5", x, bpm)
rest(0.052, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("^", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("8", x, bpm)
keypress("1", x, bpm)
rest(0.065, bpm)
keypress("*", x, bpm)
keypress("!", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("@", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
rest(0.065, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.065, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.065, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.065, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(0.065, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.065, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(0.065, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.065, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.065, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("@", x, bpm)
rest(0.065, bpm)
keypress("9", x, bpm)
keypress("2", x, bpm)
rest(0.065, bpm)
keypress("*", x, bpm)
keypress("!", x, bpm)
rest(0.065, bpm)
keypress("8", x, bpm)
keypress("1", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.052, bpm)
keypress("^", x, bpm)
rest(0.052, bpm)
keypress("6", x, bpm)
rest(0.052, bpm)
keypress("%", x, bpm)
rest(0.052, bpm)
keypress("5", x, bpm)
rest(0.052, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("^", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("8", x, bpm)
keypress("1", x, bpm)
rest(0.065, bpm)
keypress("*", x, bpm)
keypress("!", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("@", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
rest(0.065, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.065, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.065, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.065, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(0.065, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.065, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.065, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(0.065, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.065, bpm)
keypress("W", x, bpm)
keypress("%", x, bpm)
rest(0.065, bpm)
keypress("w", x, bpm)
keypress("5", x, bpm)
rest(0.065, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.065, bpm)
keypress("q", x, bpm)
keypress("4", x, bpm)
rest(0.065, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
rest(0.065, bpm)
keypress("(", x, bpm)
keypress("@", x, bpm)
rest(0.065, bpm)
keypress("9", x, bpm)
keypress("2", x, bpm)
rest(0.065, bpm)
keypress("*", x, bpm)
keypress("!", x, bpm)
rest(0.065, bpm)
keypress("8", x, bpm)
keypress("1", x, bpm)
rest(0.065, bpm)
keypress("7", x, bpm)
rest(0.052, bpm)
keypress("^", x, bpm)
rest(0.052, bpm)
keypress("6", x, bpm)
rest(0.052, bpm)
keypress("%", x, bpm)
rest(0.052, bpm)
keypress("5", x, bpm)
rest(0.052, bpm)
keypress("%", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.162, bpm)
keypress("^", x, bpm)
rest(0.135, bpm)
keypress("@", x, bpm)
rest(0.116, bpm)
keypress("%", x, bpm)
rest(0.102, bpm)
keypress("7", x, bpm)
rest(0.102, bpm)
keypress("^", x, bpm)
rest(0.102, bpm)
keypress("@", x, bpm)
rest(0.102, bpm)
keypress("%", x, bpm)
rest(0.102, bpm)
keypress("7", x, bpm)
rest(0.102, bpm)
keypress("^", x, bpm)
rest(0.102, bpm)
keypress("@", x, bpm)
rest(0.102, bpm)
keypress("%", x, bpm)
rest(0.102, bpm)
keypress("7", x, bpm)
rest(0.102, bpm)
keypress("^", x, bpm)
rest(0.102, bpm)
keypress("@", x, bpm)
rest(0.102, bpm)
keypress("%", x, bpm)
rest(0.102, bpm)
keypress("7", x, bpm)
rest(0.102, bpm)
keypress("^", x, bpm)
rest(0.102, bpm)
keypress("@", x, bpm)
rest(0.102, bpm)
keypress("%", x, bpm)
rest(0.102, bpm)
keypress("7", x, bpm)
rest(0.116, bpm)
keypress("^", x, bpm)
rest(0.135, bpm)
keypress("@", x, bpm)
rest(0.162, bpm)
keypress("%", x, bpm)
rest(0.162, bpm)
keypress("7", x, bpm)
rest(0.162, bpm)
keypress("^", x, bpm)
rest(0.162, bpm)
keypress("@", x, bpm)
rest(0.162, bpm)
keypress("%", x, bpm)
rest(0.203, bpm)
keypress("7", x, bpm)
rest(0.203, bpm)
keypress("^", x, bpm)
rest(0.203, bpm)
keypress("@", x, bpm)
rest(0.271, bpm)
keypress("%", x, bpm)
rest(17.333, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(0.722, bpm)
keypress("7", x, bpm)
rest(0.722, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.722, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.722, bpm)
keypress("r", x, bpm)
rest(0.361, bpm)
keypress("H", x, bpm)
rest(0.361, bpm)
keypress("0", x, bpm)
rest(0.722, bpm)
keypress("H", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.722, bpm)
keypress("r", x, bpm)
rest(0.361, bpm)
keypress("G", x, bpm)
rest(0.361, bpm)
keypress("0", x, bpm)
rest(0.722, bpm)
keypress("H", x, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.722, bpm)
keypress("r", x, bpm)
rest(0.361, bpm)
keypress("Z", x, bpm)
keypress("H", x, bpm)
rest(0.361, bpm)
keypress("0", x, bpm)
rest(0.722, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.722, bpm)
keypress("Q", x, bpm)
rest(0.361, bpm)
keypress("G", x, bpm)
rest(0.361, bpm)
keypress("$", x, bpm)
rest(0.722, bpm)
keypress("H", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.722, bpm)
keypress("E", x, bpm)
rest(0.361, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
rest(0.361, bpm)
keypress("Q", x, bpm)
rest(0.722, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.722, bpm)
keypress("E", x, bpm)
rest(0.361, bpm)
keypress("Z", x, bpm)
rest(0.361, bpm)
keypress("Q", x, bpm)
rest(0.722, bpm)
keypress("C", x, bpm)
keypress("T", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.722, bpm)
keypress("E", x, bpm)
rest(0.361, bpm)
keypress("L", x, bpm)
rest(0.361, bpm)
keypress("Q", x, bpm)
rest(0.722, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.722, bpm)
keypress("W", x, bpm)
rest(0.361, bpm)
keypress("Z", x, bpm)
rest(0.361, bpm)
keypress("(", x, bpm)
rest(0.722, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(1.083, bpm)
keypress("Z", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(1.083, bpm)
keypress("L", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.722, bpm)
keypress("W", x, bpm)
rest(0.361, bpm)
keypress("Z", x, bpm)
rest(0.361, bpm)
keypress("(", x, bpm)
rest(0.722, bpm)
keypress("C", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(0.722, bpm)
keypress("W", x, bpm)
rest(0.361, bpm)
keypress("L", x, bpm)
rest(0.361, bpm)
keypress("(", x, bpm)
rest(0.722, bpm)
keypress("r", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
rest(0.722, bpm)
keypress("7", x, bpm)
rest(0.361, bpm)
keypress("Z", x, bpm)
rest(0.361, bpm)
keypress("Q", x, bpm)
rest(0.722, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(1.083, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(1.083, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("L", x, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
keypress("P", x, bpm)
rest(0.722, bpm)
keypress("r", x, bpm)
rest(0.361, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
rest(0.361, bpm)
keypress("Q", x, bpm)
rest(0.722, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
keypress("7", x, bpm)
rest(1.083, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
keypress("T", x, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(9.75, bpm)
keypress("H", x, bpm)
keypress("V", x, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
keypress("3", x, bpm)
rest(0.722, bpm)
keypress("7", x, bpm)
rest(0.722, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.722, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.722, bpm)
keypress("3", x, bpm)
rest(0.361, bpm)
keypress("H", x, bpm)
rest(0.361, bpm)
keypress("7", x, bpm)
rest(0.722, bpm)
keypress("H", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.722, bpm)
keypress("3", x, bpm)
rest(0.361, bpm)
keypress("G", x, bpm)
rest(0.361, bpm)
keypress("7", x, bpm)
rest(0.722, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.722, bpm)
keypress("3", x, bpm)
rest(0.361, bpm)
keypress("Z", x, bpm)
keypress("H", x, bpm)
rest(0.361, bpm)
keypress("7", x, bpm)
rest(0.722, bpm)
keypress("H", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.722, bpm)
keypress("$", x, bpm)
rest(0.361, bpm)
keypress("G", x, bpm)
rest(0.361, bpm)
keypress("*", x, bpm)
rest(0.722, bpm)
keypress("H", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.722, bpm)
keypress("$", x, bpm)
rest(0.361, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
rest(0.361, bpm)
keypress("*", x, bpm)
rest(0.722, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.722, bpm)
keypress("$", x, bpm)
rest(0.361, bpm)
keypress("Z", x, bpm)
rest(0.361, bpm)
keypress("*", x, bpm)
rest(0.722, bpm)
keypress("C", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.722, bpm)
keypress("$", x, bpm)
rest(0.361, bpm)
keypress("L", x, bpm)
rest(0.361, bpm)
keypress("*", x, bpm)
rest(0.722, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.722, bpm)
keypress("@", x, bpm)
rest(0.361, bpm)
keypress("Z", x, bpm)
rest(0.361, bpm)
keypress("7", x, bpm)
rest(0.722, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1.083, bpm)
keypress("Z", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1.083, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.722, bpm)
keypress("@", x, bpm)
rest(0.361, bpm)
keypress("Z", x, bpm)
rest(0.361, bpm)
keypress("7", x, bpm)
rest(0.722, bpm)
keypress("C", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.722, bpm)
keypress("@", x, bpm)
rest(0.361, bpm)
keypress("L", x, bpm)
rest(0.361, bpm)
keypress("7", x, bpm)
rest(0.722, bpm)
keypress("7", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("W", x, bpm)
rest(0.722, bpm)
keypress("7", x, bpm)
rest(0.361, bpm)
keypress("Z", x, bpm)
rest(0.361, bpm)
keypress("$", x, bpm)
rest(0.722, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(1.083, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(1.083, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("L", x, bpm)
keypress("(", x, bpm)
keypress("Q", x, bpm)
keypress("E", x, bpm)
rest(0.722, bpm)
keypress("7", x, bpm)
rest(0.361, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
rest(0.361, bpm)
keypress("$", x, bpm)
rest(0.722, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("C", x, bpm)
keypress("7", x, bpm)
rest(1.083, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("Z", x, bpm)
keypress("C", x, bpm)
keypress("T", x, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)

finishedSong()