keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(20, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(4.621, bpm)
keypress("$", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(4.621, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(4.621, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(4.621, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(2.31, bpm)
keypress("I", x, bpm)
rest(1.155, bpm)
keypress("I", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(4.621, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(2.31, bpm)
keypress("a", x, bpm)
rest(1.155, bpm)
keypress("a", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(4.621, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
keypress("y", x, bpm)
rest(2.31, bpm)
keypress("I", x, bpm)
rest(1.155, bpm)
keypress("I", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(4.621, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(2.31, bpm)
keypress("a", x, bpm)
rest(1.155, bpm)
keypress("a", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(1.155, bpm)
keypress("a", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(2.31, bpm)
keypress("I", x, bpm)
rest(1.155, bpm)
keypress("I", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(2.31, bpm)
keypress("S", x, bpm)
rest(1.155, bpm)
keypress("S", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(2.31, bpm)
keypress("a", x, bpm)
rest(1.155, bpm)
keypress("a", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(1.155, bpm)
keypress("a", x, bpm)
rest(1.155, bpm)
keypress("a", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(2.31, bpm)
keypress("I", x, bpm)
rest(1.155, bpm)
keypress("I", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(2.31, bpm)
keypress("S", x, bpm)
rest(1.155, bpm)
keypress("S", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(2.31, bpm)
keypress("a", x, bpm)
rest(1.155, bpm)
keypress("a", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(1.155, bpm)
keypress("a", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("h", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("h", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.289, bpm)
keypress("d", x, bpm)
rest(0.289, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("h", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.578, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1.155, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.578, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1.155, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(1.155, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.578, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1.155, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.578, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1.155, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(1.155, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(1.733, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(2.31, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(1.155, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(1.155, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(1.155, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.578, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1.155, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.578, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1.155, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(1.155, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.578, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1.155, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.578, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1.155, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(1.155, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(1.733, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(2.31, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(1.155, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(1.155, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(1.155, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("h", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("h", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("h", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("h", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.578, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1.155, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.578, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1.155, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(1.155, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.578, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1.155, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.578, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1.155, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(1.155, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(1.733, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(2.31, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(1.155, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(1.155, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(1.155, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.578, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1.155, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.578, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(1.155, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(1.155, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.578, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1.155, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.578, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(1.155, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(1.155, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(1.733, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(2.31, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(1.155, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(1.155, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(1.155, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
rest(0.578, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.578, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("r", x, bpm)
rest(0.578, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("w", x, bpm)
rest(0.578, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.578, bpm)
keypress("w", x, bpm)

finishedSong()