rest(2.5, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.122, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.003, bpm)
keypress("4", x, bpm)
rest(0.12, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.005, bpm)
keypress("8", x, bpm)
rest(0.12, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.005, bpm)
keypress("e", x, bpm)
rest(0.117, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.008, bpm)
keypress("q", x, bpm)
rest(0.117, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.008, bpm)
keypress("t", x, bpm)
rest(0.117, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.008, bpm)
keypress("e", x, bpm)
rest(0.117, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.008, bpm)
keypress("q", x, bpm)
rest(0.115, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.01, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
rest(0.115, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.01, bpm)
keypress("e", x, bpm)
rest(0.112, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.138, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
rest(0.122, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.003, bpm)
keypress("3", x, bpm)
rest(0.12, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.005, bpm)
keypress("7", x, bpm)
rest(0.12, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.005, bpm)
keypress("w", x, bpm)
rest(0.117, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.008, bpm)
keypress("0", x, bpm)
rest(0.117, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.008, bpm)
keypress("r", x, bpm)
rest(0.117, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.008, bpm)
keypress("w", x, bpm)
rest(0.117, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.008, bpm)
keypress("0", x, bpm)
rest(0.115, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.01, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
rest(0.115, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.01, bpm)
keypress("w", x, bpm)
rest(0.112, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.138, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.003, bpm)
keypress("2", x, bpm)
rest(0.12, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.005, bpm)
keypress("6", x, bpm)
rest(0.12, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.005, bpm)
keypress("Q", x, bpm)
rest(0.117, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.008, bpm)
keypress("9", x, bpm)
rest(0.117, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.008, bpm)
keypress("e", x, bpm)
rest(0.117, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.008, bpm)
keypress("Q", x, bpm)
rest(0.117, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.008, bpm)
keypress("9", x, bpm)
rest(0.115, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.01, bpm)
keypress("$", x, bpm)
keypress("6", x, bpm)
rest(0.115, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.01, bpm)
keypress("Q", x, bpm)
rest(0.112, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
rest(0.138, bpm)
keypress("p", x, bpm)
keypress("a", x, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("u", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("q", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("q", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
keypress("u", x, bpm)
rest(0.125, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
keypress("r", x, bpm)
rest(0.125, bpm)
keypress("z", x, bpm)
rest(0.125, bpm)
keypress("x", x, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("v", x, bpm)
rest(0.125, bpm)
keypress("V", x, bpm)
keypress("u", x, bpm)
rest(0.125, bpm)
keypress("v", x, bpm)
rest(0.125, bpm)
keypress("x", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.125, bpm)
keypress("z", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
keypress("w", x, bpm)
rest(0.125, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
keypress("0", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.122, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.003, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.12, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.005, bpm)
keypress("Q", x, bpm)
rest(0.12, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.005, bpm)
keypress("Q", x, bpm)
keypress("y", x, bpm)
rest(0.117, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
rest(0.008, bpm)
keypress("e", x, bpm)
rest(0.117, bpm)
keypress("I", x, bpm)
rest(0.133, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.122, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.003, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
rest(0.12, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.005, bpm)
keypress("q", x, bpm)
rest(0.12, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.005, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
rest(0.117, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.008, bpm)
keypress("e", x, bpm)
rest(0.117, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.008, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)
rest(0.117, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.008, bpm)
keypress("t", x, bpm)
rest(0.117, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.008, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
rest(0.115, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.01, bpm)
keypress("q", x, bpm)
rest(0.115, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.01, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.112, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.013, bpm)
keypress("6", x, bpm)
rest(0.112, bpm)
keypress("j", x, bpm)
rest(0.138, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
rest(0.122, bpm)
keypress("k", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.003, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.12, bpm)
keypress("k", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.005, bpm)
keypress("w", x, bpm)
rest(0.12, bpm)
keypress("k", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.005, bpm)
keypress("w", x, bpm)
keypress("u", x, bpm)
rest(0.117, bpm)
keypress("k", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.008, bpm)
keypress("r", x, bpm)
rest(0.117, bpm)
keypress("k", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.008, bpm)
keypress("r", x, bpm)
keypress("o", x, bpm)
rest(0.117, bpm)
keypress("k", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.008, bpm)
keypress("u", x, bpm)
rest(0.117, bpm)
keypress("k", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.008, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.115, bpm)
keypress("k", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.01, bpm)
keypress("w", x, bpm)
rest(0.115, bpm)
keypress("k", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.01, bpm)
keypress("5", x, bpm)
keypress("0", x, bpm)
rest(0.112, bpm)
keypress("k", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.013, bpm)
keypress("7", x, bpm)
rest(0.112, bpm)
keypress("k", x, bpm)
rest(0.138, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.125, bpm)
keypress("L", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("L", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.125, bpm)
keypress("L", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
rest(0.125, bpm)
keypress("L", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
keypress("y", x, bpm)
rest(0.125, bpm)
keypress("L", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.125, bpm)
keypress("L", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("L", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("y", x, bpm)
rest(0.125, bpm)
keypress("L", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.125, bpm)
keypress("L", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
rest(0.125, bpm)
keypress("L", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
keypress("9", x, bpm)
rest(0.125, bpm)
keypress("L", x, bpm)
rest(0.125, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("6", x, bpm)
rest(0.125, bpm)
keypress("L", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
rest(0.122, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.003, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(0.12, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.005, bpm)
keypress("0", x, bpm)
rest(0.12, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.005, bpm)
keypress("0", x, bpm)
keypress("t", x, bpm)
rest(0.117, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.008, bpm)
keypress("w", x, bpm)
rest(0.117, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.008, bpm)
keypress("w", x, bpm)
keypress("u", x, bpm)
rest(0.117, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.008, bpm)
keypress("t", x, bpm)
rest(0.117, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.008, bpm)
keypress("5", x, bpm)
rest(0.115, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.01, bpm)
keypress("$", x, bpm)
rest(0.112, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.138, bpm)
keypress("z", x, bpm)
keypress("4", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
rest(0.125, bpm)
keypress("z", x, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.125, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("6", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(0.125, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("i", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
keypress("e", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.125, bpm)
keypress("g", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.122, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.122, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.122, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.122, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.122, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.125, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.138, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
rest(0.122, bpm)
keypress("z", x, bpm)
rest(0.003, bpm)
keypress("%", x, bpm)
rest(0.122, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
rest(0.003, bpm)
keypress("7", x, bpm)
rest(0.122, bpm)
keypress("z", x, bpm)
rest(0.003, bpm)
keypress("3", x, bpm)
rest(0.122, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
rest(0.003, bpm)
keypress("%", x, bpm)
rest(0.12, bpm)
keypress("z", x, bpm)
rest(0.005, bpm)
keypress("7", x, bpm)
rest(0.12, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
rest(0.005, bpm)
keypress("0", x, bpm)
rest(0.12, bpm)
keypress("z", x, bpm)
rest(0.005, bpm)
keypress("W", x, bpm)
rest(0.12, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
rest(0.005, bpm)
keypress("r", x, bpm)
rest(0.117, bpm)
keypress("z", x, bpm)
rest(0.008, bpm)
keypress("u", x, bpm)
rest(0.117, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
rest(0.008, bpm)
keypress("O", x, bpm)
rest(0.117, bpm)
keypress("z", x, bpm)
rest(0.008, bpm)
keypress("a", x, bpm)
rest(0.117, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
rest(0.008, bpm)
keypress("d", x, bpm)
rest(0.117, bpm)
keypress("z", x, bpm)
rest(0.008, bpm)
keypress("a", x, bpm)
rest(0.117, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
rest(0.008, bpm)
keypress("O", x, bpm)
rest(0.117, bpm)
keypress("z", x, bpm)
rest(0.008, bpm)
keypress("u", x, bpm)
rest(0.117, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
rest(0.008, bpm)
keypress("r", x, bpm)
rest(0.115, bpm)
keypress("z", x, bpm)
rest(0.01, bpm)
keypress("W", x, bpm)
rest(0.115, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
rest(0.01, bpm)
keypress("0", x, bpm)
rest(0.115, bpm)
keypress("z", x, bpm)
rest(0.01, bpm)
keypress("7", x, bpm)
rest(0.115, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
rest(0.01, bpm)
keypress("%", x, bpm)
rest(0.112, bpm)
keypress("z", x, bpm)
rest(0.013, bpm)
keypress("3", x, bpm)
rest(0.112, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
rest(0.013, bpm)
keypress("7", x, bpm)
rest(0.112, bpm)
keypress("z", x, bpm)
rest(0.013, bpm)
keypress("%", x, bpm)

finishedSong()