keypress("d", x, bpm)
keypress("9", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("0", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("o", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("o", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("0", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("9", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("P", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("P", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("P", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("P", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("o", x, bpm)
keypress("S", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)

finishedSong()