keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(4, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
rest(2, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(1.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(1.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
rest(2.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(1.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(2, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("J", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)

finishedSong()