keypress("6", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.667, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("q", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("o", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(3, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(5.667, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.333, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("3", x, bpm)
rest(0.333, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("3", x, bpm)
rest(0.333, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
rest(0.167, bpm)
keypress("o", x, bpm)
rest(0.167, bpm)
keypress("r", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("3", x, bpm)
rest(0.333, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("3", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("o", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
rest(0.333, bpm)
keypress("o", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("3", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
keypress("7", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(4.667, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("o", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.333, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
rest(0.333, bpm)
keypress("o", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("o", x, bpm)
rest(0.333, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("a", x, bpm)
rest(0.333, bpm)
keypress("o", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("o", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
keypress("%", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("W", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
rest(0.333, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.333, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("9", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("r", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
keypress("2", x, bpm)
rest(0.333, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
rest(0.333, bpm)
keypress("8", x, bpm)
rest(0.333, bpm)
keypress("6", x, bpm)
rest(0.333, bpm)
keypress("0", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(1.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("3", x, bpm)
rest(1.5, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("6", x, bpm)

finishedSong()