keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.125, bpm)
keypress("u", x, bpm)
rest(0.125, bpm)
keypress("i", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.129, bpm)
keypress("y", x, bpm)
rest(0.121, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("h", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.033, bpm)
keypress("g", x, bpm)
rest(0.035, bpm)
keypress("D", x, bpm)
rest(0.035, bpm)
keypress("d", x, bpm)
rest(0.035, bpm)
keypress("s", x, bpm)
rest(0.035, bpm)
keypress("P", x, bpm)
rest(0.037, bpm)
keypress("p", x, bpm)
rest(0.033, bpm)
keypress("o", x, bpm)
rest(0.035, bpm)
keypress("i", x, bpm)
rest(0.035, bpm)
keypress("Y", x, bpm)
rest(0.035, bpm)
keypress("y", x, bpm)
rest(0.035, bpm)
keypress("t", x, bpm)
rest(0.038, bpm)
keypress("E", x, bpm)
rest(0.033, bpm)
keypress("e", x, bpm)
rest(0.042, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.75, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("y", x, bpm)
rest(0.125, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("o", x, bpm)
rest(0.167, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
rest(0.333, bpm)
keypress("j", x, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("O", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("J", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(0.129, bpm)
keypress("h", x, bpm)
rest(0.371, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(0.129, bpm)
keypress("h", x, bpm)
rest(0.371, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("w", x, bpm)
rest(0.333, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.167, bpm)
keypress("E", x, bpm)
rest(0.167, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
rest(0.333, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(2.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("P", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)

finishedSong()