keypress("b", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("C", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(2.5, bpm)
keypress("v", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("C", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("j", x, bpm)
rest(1, bpm)
keypress("z", x, bpm)
keypress("n", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("b", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("n", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("C", x, bpm)
rest(0.125, bpm)
keypress("v", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("C", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(2.5, bpm)
keypress("v", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("b", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("v", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("C", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("n", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("8", x, bpm)
rest(0.065, bpm)
keypress("v", x, bpm)
rest(0.067, bpm)
keypress("n", x, bpm)
rest(0.069, bpm)
keypress("x", x, bpm)
rest(0.3, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(2.5, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.131, bpm)
keypress("d", x, bpm)
rest(0.133, bpm)
keypress("h", x, bpm)
rest(0.135, bpm)
keypress("k", x, bpm)
rest(0.1, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.131, bpm)
keypress("d", x, bpm)
rest(0.133, bpm)
keypress("G", x, bpm)
rest(0.135, bpm)
keypress("j", x, bpm)
rest(0.1, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("j", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("k", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.125, bpm)
keypress("9", x, bpm)
rest(0.125, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.125, bpm)
keypress("y", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.125, bpm)
keypress("e", x, bpm)
rest(0.125, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("p", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("G", x, bpm)
rest(0.167, bpm)
keypress("j", x, bpm)
rest(0.167, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.125, bpm)
keypress("w", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.125, bpm)
keypress("e", x, bpm)
rest(0.125, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.125, bpm)
keypress("w", x, bpm)
rest(0.125, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("u", x, bpm)
rest(0.125, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.125, bpm)
keypress("w", x, bpm)
rest(0.125, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.125, bpm)
keypress("0", x, bpm)
rest(0.125, bpm)
keypress("7", x, bpm)
rest(0.167, bpm)
keypress("5", x, bpm)
rest(0.167, bpm)
keypress("7", x, bpm)
rest(0.167, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.125, bpm)
keypress("Q", x, bpm)
rest(0.125, bpm)
keypress("r", x, bpm)
rest(0.125, bpm)
keypress("y", x, bpm)
rest(0.125, bpm)
keypress("I", x, bpm)
rest(0.125, bpm)
keypress("a", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
rest(0.125, bpm)
keypress("G", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
rest(0.125, bpm)
keypress("z", x, bpm)
rest(0.125, bpm)
keypress("C", x, bpm)
rest(0.125, bpm)
keypress("n", x, bpm)
rest(0.125, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("v", x, bpm)
keypress("n", x, bpm)
keypress("x", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.125, bpm)
keypress("u", x, bpm)
rest(0.125, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("d", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
rest(0.125, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
rest(0.125, bpm)
keypress("z", x, bpm)
rest(0.125, bpm)
keypress("f", x, bpm)
rest(0.125, bpm)
keypress("h", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
rest(0.125, bpm)
keypress("z", x, bpm)
rest(0.125, bpm)
keypress("v", x, bpm)
rest(0.125, bpm)
keypress("n", x, bpm)
rest(0.125, bpm)
keypress("z", x, bpm)
rest(0.125, bpm)
keypress("m", x, bpm)
rest(0.125, bpm)
keypress("n", x, bpm)
rest(0.25, bpm)
keypress("b", x, bpm)
rest(0.125, bpm)
keypress("n", x, bpm)
rest(0.125, bpm)
keypress("b", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("v", x, bpm)
rest(0.125, bpm)
keypress("C", x, bpm)
keypress("o", x, bpm)
rest(0.125, bpm)
keypress("v", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("C", x, bpm)
keypress("s", x, bpm)
rest(0.125, bpm)
keypress("x", x, bpm)
keypress("d", x, bpm)
rest(0.125, bpm)
keypress("z", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("x", x, bpm)
rest(0.125, bpm)
keypress("z", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
rest(0.125, bpm)
keypress("l", x, bpm)
rest(0.125, bpm)
keypress("k", x, bpm)
rest(0.167, bpm)
keypress("h", x, bpm)
rest(0.167, bpm)
keypress("f", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("a", x, bpm)
rest(0.167, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("h", x, bpm)
keypress("2", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)

finishedSong()