rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("c", x, bpm)
keypress("b", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("t", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("z", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("!", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("b", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("c", x, bpm)
keypress("b", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
rest(0.256, bpm)
keypress("W", x, bpm)
rest(0.027, bpm)
keypress("w", x, bpm)
rest(0.027, bpm)
keypress("Q", x, bpm)
rest(0.027, bpm)
keypress("q", x, bpm)
rest(0.027, bpm)
keypress("0", x, bpm)
rest(0.027, bpm)
keypress("(", x, bpm)
rest(0.027, bpm)
keypress("9", x, bpm)
rest(0.027, bpm)
keypress("*", x, bpm)
rest(0.029, bpm)
keypress("8", x, bpm)
rest(0.025, bpm)
keypress("7", x, bpm)
rest(0.027, bpm)
keypress("^", x, bpm)
rest(0.027, bpm)
keypress("6", x, bpm)
rest(0.027, bpm)
keypress("%", x, bpm)
rest(0.027, bpm)
keypress("5", x, bpm)
rest(0.027, bpm)
keypress("$", x, bpm)
rest(0.027, bpm)
keypress("4", x, bpm)
rest(0.027, bpm)
keypress("3", x, bpm)
rest(0.027, bpm)
keypress("@", x, bpm)
rest(0.027, bpm)
keypress("2", x, bpm)
rest(0.027, bpm)
keypress("!", x, bpm)
rest(0.027, bpm)
keypress("1", x, bpm)
rest(0.027, bpm)
keypress("7", x, bpm)
rest(0.027, bpm)
keypress("^", x, bpm)
rest(0.027, bpm)
keypress("6", x, bpm)
rest(0.027, bpm)
keypress("%", x, bpm)
rest(0.027, bpm)
keypress("5", x, bpm)
rest(0.067, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("H", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("H", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("r", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("H", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("H", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("g", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
keypress("D", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("*", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("z", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("z", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("x", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("z", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("z", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("z", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("L", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("x", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(2, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
keypress("r", x, bpm)
keypress("$", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
rest(0.75, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.388, bpm)
keypress("0", x, bpm)
rest(0.025, bpm)
keypress("(", x, bpm)
rest(0.021, bpm)
keypress("9", x, bpm)
rest(0.023, bpm)
keypress("*", x, bpm)
rest(0.023, bpm)
keypress("8", x, bpm)
rest(0.021, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
rest(0.002, bpm)
keypress("7", x, bpm)
rest(0.023, bpm)
keypress("^", x, bpm)
rest(0.023, bpm)
keypress("6", x, bpm)
rest(0.023, bpm)
keypress("%", x, bpm)
rest(0.023, bpm)
keypress("5", x, bpm)
rest(0.025, bpm)
keypress("$", x, bpm)
rest(0.021, bpm)
keypress("4", x, bpm)
rest(0.023, bpm)
keypress("3", x, bpm)
rest(0.023, bpm)
keypress("@", x, bpm)
rest(0.023, bpm)
keypress("2", x, bpm)
rest(0.042, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("c", x, bpm)
keypress("b", x, bpm)
keypress("$", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("d", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
keypress("!", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
keypress("c", x, bpm)
keypress("b", x, bpm)
keypress("$", x, bpm)
keypress("7", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("(", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("W", x, bpm)
keypress("O", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("G", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("W", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("c", x, bpm)
keypress("b", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("c", x, bpm)
keypress("b", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("6", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("7", x, bpm)
rest(0.75, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("L", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("!", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("%", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("8", x, bpm)
rest(0.25, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("V", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("k", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("*", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("c", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("T", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("t", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("T", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("V", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("c", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("T", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("r", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("i", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("V", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("k", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("*", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("c", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("*", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("T", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("W", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("e", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("b", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("V", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("x", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("L", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("C", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("L", x, bpm)
keypress("c", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("D", x, bpm)
keypress("Z", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("c", x, bpm)
keypress("*", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("C", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("s", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("6", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("%", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.25, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("D", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("g", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("H", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("L", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("k", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("H", x, bpm)
keypress("k", x, bpm)
keypress("c", x, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.25, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("L", x, bpm)
keypress("C", x, bpm)
keypress("6", x, bpm)
keypress("*", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("9", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("g", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("H", x, bpm)
keypress("!", x, bpm)
rest(0.25, bpm)
keypress("*", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("$", x, bpm)
rest(0.127, bpm)
keypress("T", x, bpm)
rest(0.127, bpm)
keypress("i", x, bpm)
rest(0.133, bpm)
keypress("O", x, bpm)

finishedSong()