keypress("E", x, bpm)
keypress("W", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("W", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("%", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("W", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("@", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1.5, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1.5, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
keypress("W", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("W", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("(", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("Y", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
keypress("t", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("t", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("Y", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("t", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("o", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
keypress("Y", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
keypress("Y", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("t", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("Y", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("8", x, bpm)
keypress("Y", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("(", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
keypress("t", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
keypress("Y", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("t", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
keypress("E", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
keypress("Y", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("!", x, bpm)
keypress("t", x, bpm)
keypress("E", x, bpm)

finishedSong()