rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("S", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(2, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("S", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(2, bpm)
keypress("o", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(2, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
rest(0.167, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(2, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1.667, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(0.75, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(1.25, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(2, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
keypress("w", x, bpm)
rest(2, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(2, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(2, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(2, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("W", x, bpm)
rest(2, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(2, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("(", x, bpm)
rest(2, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(2, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(2, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1.667, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(2, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
keypress("(", x, bpm)
keypress("W", x, bpm)
rest(1.667, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(1.333, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(2, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(2, bpm)
keypress("y", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(2, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(2, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(2, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(2, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(2, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.131, bpm)
keypress("t", x, bpm)
rest(0.133, bpm)
keypress("u", x, bpm)
rest(1.735, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1.667, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(2, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(0.667, bpm)
keypress("5", x, bpm)
rest(0.333, bpm)
keypress("^", x, bpm)
rest(0.667, bpm)
keypress("6", x, bpm)
rest(1.333, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(2, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1.667, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(2, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(1.667, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(1.333, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(2, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(2, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(2, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1.667, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.667, bpm)
keypress("y", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(2, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
keypress("%", x, bpm)
rest(1.667, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("W", x, bpm)
rest(0.667, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("O", x, bpm)
rest(1.333, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(2, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(2, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(2, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(1.667, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(0.667, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(2, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
keypress("w", x, bpm)
rest(2, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("1", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.079, bpm)
keypress("t", x, bpm)
rest(0.079, bpm)
keypress("u", x, bpm)
rest(1.508, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("5", x, bpm)
keypress("8", x, bpm)
rest(0.667, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(2, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(0.129, bpm)
keypress("p", x, bpm)
rest(0.129, bpm)
keypress("P", x, bpm)
rest(0.408, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
rest(0.667, bpm)
keypress("s", x, bpm)
rest(0.333, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.667, bpm)
keypress("s", x, bpm)
rest(0.333, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.129, bpm)
keypress("s", x, bpm)
rest(0.129, bpm)
keypress("P", x, bpm)
rest(0.408, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("D", x, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("%", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("J", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
keypress("h", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("D", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("j", x, bpm)
keypress("z", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(2, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(1.667, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.667, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(2, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
keypress("^", x, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("(", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(2, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.131, bpm)
keypress("t", x, bpm)
rest(0.133, bpm)
keypress("u", x, bpm)
rest(1.735, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(2, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("2", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(2, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(1.667, bpm)
keypress("t", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.667, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("^", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("@", x, bpm)
rest(2, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("Y", x, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("6", x, bpm)
keypress("8", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(2, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("1", x, bpm)
rest(0.131, bpm)
keypress("t", x, bpm)
rest(0.133, bpm)
keypress("u", x, bpm)
rest(1.735, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
keypress("$", x, bpm)
keypress("Q", x, bpm)
rest(1.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("Q", x, bpm)
rest(0.333, bpm)
keypress("E", x, bpm)
rest(0.333, bpm)
keypress("T", x, bpm)
rest(0.333, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
keypress("4", x, bpm)
keypress("8", x, bpm)
keypress("q", x, bpm)
rest(2, bpm)
keypress("4", x, bpm)
rest(2, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(2, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.667, bpm)
keypress("$", x, bpm)
rest(0.333, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("5", x, bpm)
rest(2, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(2, bpm)
keypress("s", x, bpm)
rest(0.333, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("G", x, bpm)
keypress("J", x, bpm)
rest(0.333, bpm)
keypress("l", x, bpm)
rest(0.833, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("s", x, bpm)
rest(1.167, bpm)
keypress("e", x, bpm)
keypress("4", x, bpm)
keypress("(", x, bpm)
rest(4.133, bpm)
keypress("P", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("S", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(2, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("S", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
keypress("W", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("g", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(2, bpm)
keypress("Y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("d", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(2, bpm)
keypress("o", x, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
rest(0.333, bpm)
keypress("O", x, bpm)
rest(0.333, bpm)
keypress("p", x, bpm)
rest(0.333, bpm)
keypress("P", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(2, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.167, bpm)
keypress("s", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
rest(0.167, bpm)
keypress("p", x, bpm)
keypress("q", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
keypress("Y", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(4, bpm)
keypress("^", x, bpm)
keypress("4", x, bpm)
keypress("^", x, bpm)
keypress("9", x, bpm)

finishedSong()