rest(3, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
rest(4, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(1.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("H", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(2.5, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(1.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(1.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("k", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("k", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("k", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("G", x, bpm)
keypress("L", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("k", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("j", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("k", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("!", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
keypress("!", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(1.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("5", x, bpm)
rest(1, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("H", x, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(2.5, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(1.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(1.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("2", x, bpm)
rest(0.429, bpm)
keypress("y", x, bpm)
rest(0.071, bpm)
keypress("2", x, bpm)
rest(0.356, bpm)
keypress("p", x, bpm)
rest(0.144, bpm)
keypress("2", x, bpm)
rest(0.429, bpm)
keypress("y", x, bpm)
rest(0.071, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.429, bpm)
keypress("u", x, bpm)
rest(0.071, bpm)
keypress("3", x, bpm)
rest(0.356, bpm)
keypress("p", x, bpm)
rest(0.144, bpm)
keypress("3", x, bpm)
rest(0.429, bpm)
keypress("u", x, bpm)
rest(0.071, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
rest(0.071, bpm)
keypress("$", x, bpm)
rest(0.356, bpm)
keypress("p", x, bpm)
rest(0.144, bpm)
keypress("$", x, bpm)
rest(0.429, bpm)
keypress("I", x, bpm)
rest(0.071, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("f", x, bpm)
keypress("H", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(2.5, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(1.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("O", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("O", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.031, bpm)
keypress("0", x, bpm)
rest(0.469, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("*", x, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
keypress("*", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("Q", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(1.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("H", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("H", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("*", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("j", x, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
keypress("Q", x, bpm)
rest(1, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("$", x, bpm)
rest(0.5, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("7", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("%", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("$", x, bpm)
rest(1, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
rest(1, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("O", x, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("I", x, bpm)
keypress("O", x, bpm)
rest(4, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
keypress("O", x, bpm)
rest(1, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("W", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("p", x, bpm)
keypress("G", x, bpm)
keypress("Q", x, bpm)

finishedSong()