keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("1", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(3.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(3, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(2.25, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(3.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(2, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("4", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("1", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("4", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
keypress("4", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("4", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("k", x, bpm)
rest(0.5, bpm)
keypress("l", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("z", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("x", x, bpm)
keypress("3", x, bpm)
rest(1, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(3, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.75, bpm)
keypress("o", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.75, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(3.5, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("1", x, bpm)
keypress("8", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("3", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(2.25, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(2.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(4, bpm)
keypress("f", x, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(1, bpm)
keypress("a", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(2, bpm)
keypress("a", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.085, bpm)
keypress("w", x, bpm)
rest(0.09, bpm)
keypress("t", x, bpm)
rest(1.825, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1.5, bpm)
keypress("a", x, bpm)
rest(0.75, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
rest(0.085, bpm)
keypress("w", x, bpm)
rest(0.09, bpm)
keypress("t", x, bpm)
rest(1.575, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("a", x, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(1.5, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("8", x, bpm)
keypress("w", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(1.5, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(2, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
rest(2, bpm)
keypress("y", x, bpm)
rest(0.75, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("r", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(2, bpm)
keypress("t", x, bpm)
rest(0.75, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
keypress("w", x, bpm)
keypress("r", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)

finishedSong()