keypress("J", x, bpm)
keypress("P", x, bpm)
rest(0.081, bpm)
keypress("z", x, bpm)
rest(0.083, bpm)
keypress("x", x, bpm)
rest(0.335, bpm)
keypress("z", x, bpm)
rest(1, bpm)
keypress("l", x, bpm)
rest(1.5, bpm)
keypress("f", x, bpm)
keypress("u", x, bpm)
rest(0.081, bpm)
keypress("j", x, bpm)
rest(0.419, bpm)
keypress("d", x, bpm)
rest(1, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
rest(0.081, bpm)
keypress("f", x, bpm)
rest(0.083, bpm)
keypress("j", x, bpm)
rest(0.335, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
rest(0.081, bpm)
keypress("d", x, bpm)
rest(0.083, bpm)
keypress("f", x, bpm)
rest(0.335, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("3", x, bpm)
rest(1.5, bpm)
keypress("Y", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("@", x, bpm)
rest(4.5, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(1.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("(", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("*", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
rest(1, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("e", x, bpm)
rest(0.081, bpm)
keypress("p", x, bpm)
keypress("t", x, bpm)
rest(0.084, bpm)
keypress("u", x, bpm)
rest(0.834, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
rest(1.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("q", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("u", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("o", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("i", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("q", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("u", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("9", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
rest(0.167, bpm)
keypress("^", x, bpm)
rest(0.167, bpm)
keypress("9", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("(", x, bpm)
rest(0.167, bpm)
keypress("E", x, bpm)
rest(0.167, bpm)
keypress("y", x, bpm)
rest(0.167, bpm)
keypress("Y", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
rest(0.167, bpm)
keypress("D", x, bpm)
rest(0.167, bpm)
keypress("P", x, bpm)
keypress("h", x, bpm)
keypress("@", x, bpm)
rest(1.5, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("y", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("5", x, bpm)
keypress("w", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.167, bpm)
keypress("p", x, bpm)
keypress("4", x, bpm)
rest(0.167, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(0.167, bpm)
keypress("t", x, bpm)
keypress("9", x, bpm)
rest(0.167, bpm)
keypress("y", x, bpm)
keypress("q", x, bpm)
rest(0.167, bpm)
keypress("E", x, bpm)
keypress("e", x, bpm)
rest(0.167, bpm)
keypress("e", x, bpm)
keypress("q", x, bpm)
rest(0.167, bpm)
keypress("q", x, bpm)
keypress("9", x, bpm)
rest(0.167, bpm)
keypress("9", x, bpm)
keypress("^", x, bpm)
rest(0.167, bpm)
keypress("@", x, bpm)
rest(0.1, bpm)
keypress("(", x, bpm)
rest(0.1, bpm)
keypress("q", x, bpm)
rest(0.1, bpm)
keypress("w", x, bpm)
rest(0.1, bpm)
keypress("E", x, bpm)
rest(0.1, bpm)
keypress("Y", x, bpm)
rest(0.1, bpm)
keypress("P", x, bpm)
rest(0.1, bpm)
keypress("D", x, bpm)
rest(0.1, bpm)
keypress("g", x, bpm)
rest(0.1, bpm)
keypress("h", x, bpm)
rest(0.1, bpm)
keypress("s", x, bpm)
keypress("l", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("I", x, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("0", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("h", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("G", x, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("h", x, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("G", x, bpm)
keypress("I", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("a", x, bpm)
keypress("Q", x, bpm)
keypress("e", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
keypress("p", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("a", x, bpm)
keypress("d", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("S", x, bpm)
keypress("f", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("r", x, bpm)
keypress("y", x, bpm)
keypress("I", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("h", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("g", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("1", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("0", x, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("3", x, bpm)
rest(0.5, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("o", x, bpm)
keypress("9", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("P", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
keypress("8", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("^", x, bpm)
rest(3, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("j", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("S", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("D", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("H", x, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("l", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("s", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.5, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("Y", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("O", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("f", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("w", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("t", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.25, bpm)
keypress("E", x, bpm)
rest(0.25, bpm)
keypress("o", x, bpm)
keypress("p", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("u", x, bpm)
rest(0.25, bpm)
keypress("i", x, bpm)
rest(0.25, bpm)
keypress("P", x, bpm)
keypress("g", x, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
keypress("j", x, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.25, bpm)
keypress("j", x, bpm)
keypress("l", x, bpm)
rest(1.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1.5, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("P", x, bpm)
keypress("6", x, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("d", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("f", x, bpm)
keypress("j", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("P", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("i", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("d", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(1, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("T", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("y", x, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("o", x, bpm)
keypress("s", x, bpm)
keypress("@", x, bpm)
rest(0.5, bpm)
keypress("P", x, bpm)
keypress("d", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
rest(2.5, bpm)
keypress("y", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
keypress("E", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("w", x, bpm)
keypress("e", x, bpm)
keypress("T", x, bpm)
rest(1, bpm)
keypress("u", x, bpm)
keypress("5", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("w", x, bpm)
keypress("E", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("E", x, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("S", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("4", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(1.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
rest(1.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
rest(1.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("E", x, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("E", x, bpm)
rest(1.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(1.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
rest(1.5, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
keypress("p", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("q", x, bpm)
keypress("t", x, bpm)
rest(1.5, bpm)
keypress("q", x, bpm)
keypress("E", x, bpm)
rest(1.5, bpm)
keypress("E", x, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("o", x, bpm)
keypress("2", x, bpm)
rest(1.5, bpm)
keypress("t", x, bpm)
keypress("o", x, bpm)
rest(1.5, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("6", x, bpm)
rest(0.5, bpm)
keypress("0", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("d", x, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("i", x, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("d", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("o", x, bpm)
rest(0.25, bpm)
keypress("p", x, bpm)
rest(0.25, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
keypress("q", x, bpm)
rest(0.25, bpm)
keypress("y", x, bpm)
rest(0.25, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("u", x, bpm)
keypress("2", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(1, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("t", x, bpm)
keypress("2", x, bpm)
rest(1, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
rest(0.5, bpm)
keypress("s", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("^", x, bpm)
rest(0.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("u", x, bpm)
keypress("E", x, bpm)
rest(1.5, bpm)
keypress("y", x, bpm)
keypress("^", x, bpm)
rest(1.5, bpm)
keypress("q", x, bpm)
rest(0.5, bpm)
keypress("t", x, bpm)
rest(0.5, bpm)
keypress("i", x, bpm)
rest(0.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
keypress("9", x, bpm)
rest(1.5, bpm)
keypress("e", x, bpm)
keypress("y", x, bpm)
keypress("u", x, bpm)
rest(1.5, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
rest(1.25, bpm)
keypress("f", x, bpm)
rest(0.25, bpm)
keypress("g", x, bpm)
rest(0.5, bpm)
keypress("f", x, bpm)
rest(0.5, bpm)
keypress("p", x, bpm)
rest(0.5, bpm)
keypress("y", x, bpm)
keypress("p", x, bpm)
keypress("s", x, bpm)
keypress("^", x, bpm)
rest(2.489, bpm)
keypress("t", x, bpm)
keypress("i", x, bpm)
keypress("p", x, bpm)
keypress("^", x, bpm)
rest(2.489, bpm)
keypress("t", x, bpm)
keypress("^", x, bpm)
keypress("8", x, bpm)

finishedSong()